### ISSUE TITLE
it thinks 'lame' is a file or directory

### ISSUE THREAD

**Issue by zohaad** [muammar/mkchromecast#123]
[2017-12-15 19:39:00,681] ERROR in app: Exception on /stream [GET]
Traceback (most recent call last):
  File "/home/zohaad/anaconda3/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/zohaad/anaconda3/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/zohaad/anaconda3/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/zohaad/anaconda3/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/zohaad/anaconda3/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/zohaad/anaconda3/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/zohaad/git_folder/mkchromecast/mkchromecast/audio.py", line 670, in stream
    process = Popen(command, stdin=parec.stdout, stdout=PIPE, bufsize=-1)
  File "/home/zohaad/anaconda3/lib/python3.5/subprocess.py", line 947, in \_\_init\_\_
    restore_signals, start_new_session)
  File "/home/zohaad/anaconda3/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'lame'
192.168.2.7 - - [15/Dec/2017 19:39:00] "GET /stream HTTP/1.1" 500 -
^CKilled

**Comment by muammar** [comment]
This is strange to me. I don't use Anaconda. Were you able to fix this issue?

**Comment by zohaad** [comment]
It was a while back but I got it working by not using 5ghz wifi. This is probably unrelated to the issue. I don't remember the specifics anymore, sorry.

**Comment by muammar** [comment]
Thanks for replying. I will proceed to close this report.
