### ISSUE TITLE
No audio on Fedora 27 

### ISSUE THREAD

**Issue by erikindre** [muammar/mkchromecast#142]
Running mkchromecast-0.3.8.1 on Fedora 27. Followed the instructions on https://github.com/muammar/mkchromecast#from-sources. I can connect and get no error messages, but there is no sounds. The only odd thing I noticed is that after opening pavucontrol the VU meter indicates audio is playing from Spotify, but the "null output" device is selected. When clicking the selector, it is clear that it is in fact mkchromecast that is selected. I try to switch back and forth between mkchromecast and built-in audio but I can not get any audio through the mkcrhomecast device.

[erik@yoga-900-fedora mkchromecast]$ python mkchromecast.py
Mkchromecast v0.3.8.1
Creating Pulseaudio Sink...
Open Pavucontrol and Select the Mkchromecast Sink.
Starting Local Streaming Server
[Done]
Selected backend: parec
Selected audio codec: mp3
Default bitrate used: 192k
Default sample rate used: 44100Hz.
PID of main process: 10239
PID of streaming process: 10248
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
^[ 
List of Devices Available in Network:
-------------------------------------

Index   Types   Friendly Name 
=====   =====   ============= 
0 	Gcast 	Erik_audio
1 	Gcast 	Living Room Display
2 	Gcast 	ChromecastUltra7195
 
Casting to first device shown above!
Select devices by using the -s flag.
 
Erik_audio
 
 
Information about  Erik_audio
 
DeviceStatus(friendly_name=u'Erik_audio', model_name=u'Chromecast Audio', manufacturer=u'Google Inc.', uuid=UUID('62493fc9-f0ca-58de-c1ef-20a526d1976b'), cast_type='audio')
 
Status of device  Erik_audio
 
CastStatus(is_active_input=None, is_stand_by=None, volume_level=1.0, volume_muted=False, app_id=None, display_name=None, namespaces=[], session_id=None, transport_id=None, status_text='')
 
The IP of Erik_audio is: 192.168.1.114
Your local IP is: 192.168.1.177
 
The media type string used is: audio/mpeg
 
Cast media controller status
 
CastStatus(is_active_input=None, is_stand_by=None, volume_level=1.0, volume_muted=False, app_id=None, display_name=None, namespaces=[], session_id=None, transport_id=None, status_text='')
 
Remember to open pavucontrol and select the mkchromecast sink.

Ctrl-C to kill the Application at any Time

**Comment by sagarun** [comment]
I get the same as well.

**Comment by sagarun** [comment]
python3 mkchromecast.py -i ~/Downloads/Video.mkv  --debug
ALSA device name: None.
Google Cast name: None.
backends:  ['ffmpeg', 'avconv', 'parec', 'gstreamer']
ALSA device name: None.
Google Cast name: None.
backends:  ['ffmpeg', 'avconv', 'parec', 'gstreamer']
USER =saga
PATH =/usr/lib64/qt-3.3/bin:/usr/share/Modules/bin:/home/saga/.rvm/gems/ruby-2.3.0/bin:/home/saga/.rvm/gems/ruby-2.3.0@global/bin:/home/saga/.rvm/rubies/ruby-2.3.0/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/saga/.rvm/bin:/home/saga/.local/bin:/home/saga/bin:/home/saga/.local/bin:/home/saga/bin
Mkchromecast v0.3.8.1
:::cast::: sockets method 192.168.0.166
Creating Pulseaudio Sink...
Open Pavucontrol and Select the Mkchromecast Sink.
Starting Local Streaming Server
[Done]
:::audio::: chunk_size, frame_size, buffer_size: 64, 2048, 8192
Selected backend: parec
Selected audio codec: mp3
Default bitrate used: 192k
Default sample rate used: 44100Hz.
:::audio::: command ['lame', '-b', '192', '-r', '-']
PID of main process: 31374
PID of streaming process: 31381
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
self.cclist [[0, 'Living Room TV', 'Gcast']]
if len(self.cclist) != 0 and self.select_cc == False:
 
List of Devices Available in Network:
-------------------------------------

Index   Types   Friendly Name 
=====   =====   ============= 
0 	Gcast 	Living Room TV
 
Casting to first device shown above!
Select devices by using the -s flag.
 
Living Room TV
 
def get_cc(self):
 
Information about  Living Room TV
 
DeviceStatus(friendly_name='Living Room TV', model_name='Chromecast', manufacturer='Google Inc.', uuid=UUID('e2ad518b-d9f2-05db-03d3-7c75007866d9'), cast_type='cast')
 
Status of device  Living Room TV
 
CastStatus(is_active_input=False, is_stand_by=True, volume_level=1.0, volume_muted=False, app_id='E8C28D3C', display_name='Backdrop', namespaces=['urn:x-cast:com.google.cast.debugoverlay', 'urn:x-cast:com.google.cast.cac', 'urn:x-cast:com.google.cast.sse'], session_id='72f73b77-bf41-4a63-aacb-d624518dc595', transport_id='72f73b77-bf41-4a63-aacb-d624518dc595', status_text='')
 
def play_cast(self):
The IP of Living Room TV is: 192.168.0.168
Your local IP is: 192.168.0.166
 
The media type string used is: audio/mpeg
 
Cast media controller status
 
CastStatus(is_active_input=False, is_stand_by=True, volume_level=1.0, volume_muted=False, app_id='E8C28D3C', display_name='Backdrop', namespaces=['urn:x-cast:com.google.cast.debugoverlay', 'urn:x-cast:com.google.cast.cac', 'urn:x-cast:com.google.cast.sse'], session_id='72f73b77-bf41-4a63-aacb-d624518dc595', transport_id='72f73b77-bf41-4a63-aacb-d624518dc595', status_text='')
 
Remember to open pavucontrol and select the mkchromecast sink.

Ctrl-C to kill the Application at any Time

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/site-packages/pychromecast/socket_client.py", line 341, in run
    if self.run_once() == 1:
  File "/usr/lib/python3.6/site-packages/pychromecast/socket_client.py", line 406, in run_once
    function(data)
  File "/usr/lib/python3.6/site-packages/pychromecast/socket_client.py", line 830, in <lambda>
    self._block_till_launched(app_id))
  File "/usr/lib/python3.6/site-packages/pychromecast/socket_client.py", line 843, in _block_till_launched
    app_id, self.launch_failure.reason))
pychromecast.error.LaunchError: Failed to launch app: CC1AD845, Reason: NOT_FOUND
