### ISSUE TITLE
Fedora 28 Install Instructions

### ISSUE THREAD

**Issue by TheRoarkster** [muammar/mkchromecast#192]
Please improve the instructions for installs on non-buntu based systems?   

Downloading the source, as described in the instructions, is not the end of the install story.  But trying to figure out the correct steps after that have eluded me.

If anyone other than @muammar can provide Fedora install instructions, that would be awesome.  I'm sure it would help others, and @muammar could add them to the install instructions.

**Comment by r3d3mpt10n** [comment]
I've git cloned it and installed all of the packages from the requirements.txt.

When I try to run the application, I'm getting: 
Mkchromecast v0.3.8.1
Creating Pulseaudio Sink...
Open Pavucontrol and Select the Mkchromecast Sink.
Starting Local Streaming Server
[Done]
Selected backend: parec
Selected audio codec: mp3
Default bitrate used: 192k
Default sample rate used: 44100Hz.
PID of main process: 31068
 * Serving Flask app "mkchromecast.audio" (lazy loading)
PID of streaming process: 31075
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
Exception in thread zeroconf-Engine:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 804, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/site-packages/zeroconf.py", line 1133, in run
    reader.handle_read(socket_)
  File "/usr/lib/python2.7/site-packages/zeroconf.py", line 1175, in handle_read
    msg = DNSIncoming(data)
  File "/usr/lib/python2.7/site-packages/zeroconf.py", line 644, in __init__
    self.read_questions()
  File "/usr/lib/python2.7/site-packages/zeroconf.py", line 667, in read_questions
    name = self.read_name()
  File "/usr/lib/python2.7/site-packages/zeroconf.py", line 756, in read_name
    t = length & 0xC0
TypeError: unsupported operand type(s) for &: 'str' and 'int'

 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
No devices found!
Cleaning up /tmp/...
[Done]
Killed


Is that the same for you @TheRoarkster ?

**Comment by zerobabble** [comment]
$ sudo dnf install python3-chromecast.noarch python3-flask.noarch python3-qt5.x86_64 lame.x86_64
$ git clone https://github.com/muammar/mkchromecast.git
$ python3 mkchromecast.py -n "YOUR_DEVICE_NAME"

- I am only using it for audio right now with pithos and have not tried video.
- It also works with python2 with python2 dependencies.
- The tray icon is not working on F27/KDE (https://github.com/muammar/mkchromecast/issues/163) with either version of python.

**Comment by TheRoarkster** [comment]
I tried @zerobabble's insructions.  All fine until I try to run it via python3.  The error reported is:

```
Traceback (most recent call last):
  File "mkchromecast.py", line 5, in <module>
    import mkchromecast.__init__
  File "/home/user/mkchromecast/mkchromecast/__init__.py", line 6, in <module>
    from mkchromecast.utils import terminate, check_url
  File "/home/user/mkchromecast/mkchromecast/utils.py", line 6, in <module>
    import psutil
ModuleNotFoundError: No module named 'psutil'
```
@muammar, I downloaded the branch you referenced above, but cannot create the fedora package.

**Comment by zerobabble** [comment]
@TheRoarkster forgot one... dnf install python3-psutil.x86_64

**Comment by TheRoarkster** [comment]
Thanks @zerobabble, that seemed to handle the install -- at least for CLI implementation of mkchromecast.  But I get a Sonos-related error when trying to cast (note:  I am not using Sonos, just a Chromecast Audio):

```
Mkchromecast v0.3.8.1
Creating Pulseaudio Sink...
Open Pavucontrol and Select the Mkchromecast Sink.
Starting Local Streaming Server
[Done]
Selected backend: parec
Selected audio codec: mp3
Default bitrate used: 192k
Default sample rate used: 44100Hz.
PID of main process: 27695
PID of streaming process: 27704
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
Traceback (most recent call last):
  File "/home/user/mkchromecast/mkchromecast/cast.py", line 310, in play_cast
    ' ' + self.cast.host)
AttributeError: 'casting' object has no attribute 'cast'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mkchromecast.py", line 283, in <module>
    mk()
  File "mkchromecast.py", line 53, in __init__
    self.audio_linux()
  File "mkchromecast.py", line 74, in audio_linux
    self.cc.play_cast()
  File "/home/user/mkchromecast/mkchromecast/cast.py", line 316, in play_cast
    for _ in self.sonos_list:
AttributeError: 'casting' object has no attribute 'sonos_list'
```

**Comment by muammar** [comment]
@TheRoarkster do you have `Soco` installed?

`pip2 install soco`

**Comment by TheRoarkster** [comment]
I just tried and got: 
`Collecting soco
  Using cached https://files.pythonhosted.org/packages/a1/39/51d65b12e7be8fb2e2709893bd0635f605d5c331c5c5fe4141bc64434bb8/soco-0.15-py2.py3-none-any.whl
Collecting xmltodict (from soco)
  Using cached https://files.pythonhosted.org/packages/42/a9/7e99652c6bc619d19d58cdd8c47560730eb5825d43a7e25db2e1d776ceb7/xmltodict-0.11.0-py2.py3-none-any.whl
Requirement already satisfied: requests in /usr/lib/python2.7/site-packages (from soco)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/lib/python2.7/site-packages (from requests->soco)
Requirement already satisfied: idna<2.7,>=2.5 in /usr/lib/python2.7/site-packages (from requests->soco)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /usr/lib/python2.7/site-packages (from requests->soco)
Installing collected packages: xmltodict, soco
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/site-packages/pip/commands/install.py", line 365, in run
    strip_file_prefix=options.strip_file_prefix,
  File "/usr/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/lib/python2.7/site-packages/pip/req/req_install.py", line 854, in install
    strip_file_prefix=strip_file_prefix
  File "/usr/lib/python2.7/site-packages/pip/req/req_install.py", line 1069, in move_wheel_files
    strip_file_prefix=strip_file_prefix,
  File "/usr/lib/python2.7/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/lib/python2.7/site-packages/pip/wheel.py", line 323, in clobber
    shutil.copyfile(srcfile, destfile)
  File "/usr/lib64/python2.7/shutil.py", line 97, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: '/usr/lib/python2.7/site-packages/xmltodict.pyc'
`

**Comment by muammar** [comment]
@TheRoarkster I misread your comment and you are not using Sonos at all. Let me investigate more into this problem. If I understand correctly you are using the `master` branch. Correct?

**Comment by TheRoarkster** [comment]
I was able to get mkchromecast to run, without explicit error, from the CLI.  But despite selecting the mkchromecast sink in pavucontrol, no sound is outputted from the speakers.  

```
python3 mkchromecast.py 
Mkchromecast v0.3.8.1
Creating Pulseaudio Sink...
Open Pavucontrol and Select the Mkchromecast Sink.
Starting Local Streaming Server
[Done]
Selected backend: parec
Selected audio codec: mp3
Default bitrate used: 192k
Default sample rate used: 44100Hz.
PID of main process: 28586
PID of streaming process: 28595
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 
List of Devices Available in Network:
-------------------------------------

Index   Types   Friendly Name 
=====   =====   ============= 
0 	Gcast 	Dining Room
1 	Gcast 	Bedroom
2 	Gcast 	Dining Room and Back
 
Casting to first device shown above!
Select devices by using the -s flag.
 
Dining Room
 
Information about  Dining Room

DeviceStatus(friendly_name='Dining Room', model_name='Chromecast Audio', manufacturer='Google Inc.', uuid=UUID('3c'), cast_type='audio')
 
Status of device  Dining Room
 
CastStatus(is_active_input=None, is_stand_by=None, volume_level=0.3499999940395355, volume_muted=False, app_id=None, display_name=None, namespaces=[], session_id=None, transport_id=None, status_text='')
 
The IP of Dining Room is: 10.3.1.23
Your local IP is: 10.7.7.132
 
The media type string used is: audio/mpeg
 
Cast media controller status
 
CastStatus(is_active_input=None, is_stand_by=None, volume_level=0.3499999940395355, volume_muted=False, app_id=None, display_name=None, namespaces=[], session_id=None, transport_id=None, status_text='')
 
Remember to open pavucontrol and select the mkchromecast sink.

Ctrl-C to kill the Application at any Time
```

**Comment by muammar** [comment]
The `Null` for the sink name is not a big issue. Can you see activity in pavucontrol? You can also pass the `--control` flag to turn your chromecast volume up.

**Comment by TheRoarkster** [comment]
I am able to see activity in pavucontrol (see  attached).  I passed the `--control` flag, but was not able get sound or change volume
![screenshot from 2018-07-10 17-58-18](https://user-images.githubusercontent.com/35146738/42545158-05c0bb5e-846b-11e8-82aa-9111535d84de.png)
.

**Comment by bugzy** [comment]
FWIW: There are rpms based on the fedora branch spec with a few modifications at:
https://copr.fedorainfracloud.org/coprs/bugzy/mkchromecast/

**Comment by didierga** [comment]
Running Fedora 28, I installed mkchromecast from https://copr.fedorainfracloud.org/coprs/bugzy/mkchromecast/ and I am able to display a mp4 on my TV using command line.
Is there a program who use mkchromecast and who permit skip fw, skip bw, pause, restart, ... ?

**Comment by pwd-github** [comment]
@bugzy for some reason, your repo is telling me that it's failed to synchronize. I'm on Fedora 29, could that be why?

**Comment by bugzy** [comment]
@pwd-github. That is probably why. I currently have Fedora 29 builds turned off; I will turn it on but I will probably have no time to fix/adjust things if there are issues.

**Comment by pwd-github** [comment]
@bugzy thank you, I'll give it a go in the morning

**Comment by pwd-github** [comment]
As the copr is down, I've not been able to install it that way, thus I've tried to do follow the instructions to pull it from git. However when I do that.. and I run the pip command, I see
```  Could not find a version that satisfies the requirement PyQt5==5.11.2 (from -r requirements.txt (line 5)) (from versions: )
No matching distribution found for PyQt5==5.11.2 (from -r requirements.txt (line 5))
```
Despite having installed the packages mentioned in @zerobabble 's post above

Also attempting to run ```python3 mkchromecast.py
python3: can't open file 'mkchromecast.py': [Errno 2] No such file or directory```

Which leaves me utterly confused

**Comment by bugzy** [comment]
@pwd-github 
copr should be back in action

**Comment by pwd-github** [comment]
@bugzy Thank you so much!

**Comment by bendem** [comment]
@bugzy, Do you have plans to provide support for the latest fedora versions ?

**Comment by bugzy** [comment]
@bendem Updated the copr for support through f33 a little while back when I saw this, but I forgot to respond here.
