### ISSUE TITLE
No sound on Ubuntu / Chromecast Audio

### ISSUE THREAD

**Issue by jfrench206** [muammar/mkchromecast#199]
Hi, I looked around but it seems like the folks with the "no audio" issue are on Mac OS. I am using Ubuntu 16.04 and have just tried running from the git cloned directory, using `python mkchromecast.py -n "my-speakername" -c aac` although the codec doesn't seem to make a difference. 

I can successfully connect to the Chromecast Audio device (get a success tone) and select the output correctly in pavucontrol, which shows audio levels going to mkchromecast, but I hear no sound.

I notice in console I do get this error when running the script with debug mode: 

```
Exception in thread Thread-11:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/dist-packages/zeroconf.py", line 1063, in run
    handler(self.zc)
  File "/usr/lib/python2.7/dist-packages/zeroconf.py", line 1014, in <lambda>
    state_change=state_change,
  File "/usr/lib/python2.7/dist-packages/zeroconf.py", line 931, in fire
    h(**kwargs)
  File "/usr/lib/python2.7/dist-packages/zeroconf.py", line 989, in on_change
    listener.add_service(*args)
  File "/usr/lib/python2.7/dist-packages/pychromecast/discovery.py", line 58, in add_service
    model_name = get_value('md')
  File "/usr/lib/python2.7/dist-packages/pychromecast/discovery.py", line 49, in get_value
    value = service.properties.get(key.encode('utf-8'))
  File "/usr/lib/python2.7/dist-packages/zeroconf.py", line 1100, in properties
    return self._properties
AttributeError: 'ServiceInfo' object has no attribute '_properties'
```

**Comment by muammar** [comment]
Hi, 

Can you try with Python3? I think this is related to #154.

**Comment by jfrench206** [comment]
Hmmm...I'm not at work with the Chromecast Audio I was trying, but I have a full-on Chromecast at home it turns out. Running `python3 mkchromecast.py --debug` gives no errors...but I still don't get audio. 

The Chromecast responds to mkchromecast connection, displaying a little text about it on the TV, and I can select the sink in pavucontrol and see audio levels...but no sound :(

**Comment by philba** [comment]
I am having the same problem on Ubuntu 18.04. Everything installs and Mkchromecast is selected as the output device. I also get a success tone from my chromecast when first connected, however I am unable to get any audio output when playing files. If I cast from Chrome or from Google Play Music, everything works fine, so the issue seems to be with Mkchromecast. In my cast, the cast status reads:

Casting to: Home Stereo speaker
Information about  Home Stereo speaker
 
DeviceStatus(friendly_name='Home Stereo speaker', model_name='Chromecast Audio', manufacturer=None, api_version=None, uuid=UUID('3e57ad4a-d86a-56ad-adfd-89d57a0f2e02'), cast_type='audio')
 
Status of device  Home Stereo speaker
CastStatus(is_active_input=None, is_stand_by=None, volume_level=0.25, volume_muted=False, app_id=None, display_name=None, namespaces=[], session_id=None, transport_id=None, status_text='')
 
The IP of Home Stereo speaker is: 192.168.1.109
Your local IP is: 192.168.1.105
 
The media type string used is: audio/mpeg
 
Cast media controller status
CastStatus(is_active_input=None, is_stand_by=None, volume_level=0.25, volume_muted=False, app_id=None, display_name=None, namespaces=[], session_id=None, transport_id=None, status_text='')_

**Comment by hyproman** [comment]
I believe I have a fix for this issue. My understanding of the root cause is that the Flask app always listens on IP address `0.0.0.0`, regardless of the presence of `--host` parameter or external IP address detected. The Flask `app.run(...)` is hard-coded in all places to listen on `0.0.0.0`. Passing the non-internal IP (from `--host` or from the detection logic used in other places) gets my Ubuntu 18.04 laptop streaming audio to my Chromecast-Ultra.

I'd be happy to get a PR going; unfortunately I can't push my feature branch; guessing I need to be added as a collaborator?

**Comment by muammar** [comment]
@hyproman that is strange. I normally get PR that I am very happy to include. Did you clone the repo in your account?

**Comment by hyproman** [comment]
@muammar that was my bad; I hadn't forked and was trying to push a feature branch directly to your repo's origin. I'm probably the last dev on the planet still getting used to Github workflow (always worked at places that ran their own git servers).

Anyhow, after all that, I actually don't know if a change is necessary. It turns out that my environment works with Flask listening at `0.0.0.0:5000`. In my case, I had to allow non-local access to port `5000` through the firewall on the laptop (UFW).

**For others still having problems on Ubuntu**, check if you have the firewall running:  `sudo ufw status`
If it is `active`:
- Try temporarily disabling `sudo ufw disable` (use `sudo ufw enable` to turn back on).
OR
- Add a rule to allow access to the Flask app:
`sudo ufw allow to any port 5000`
or...more restrictively:
`sudo ufw allow from CHROMECAST_IP_HERE to any port 5000`, replacing CHROMECAST_IP_HERE with...hopefully you get the idea.
- Restart **mkchromecast**

If all goes well, you should see some output from **mkchromecast** about a request /stream (last line below):
```
Ctrl-C to kill the Application at any Time

192.168.1.50 - - [13/Dec/2018 10:35:07] "GET /stream HTTP/1.1" 200 -
```
Prior to making the firewall changes, I was unable to see any of those request messages.

**Comment by hyproman** [comment]
...and the PR for the original thought:
https://github.com/muammar/mkchromecast/pull/224
