### ISSUE TITLE
Exception error

### ISSUE THREAD

**Issue by mattomatto** [muammar/mkchromecast#22]
Hi there, 

I'm running mkchromecast on Raspbian.  I have installed all of the dependancies manually and have used pip3 since I couldn't get pip to install the packages properly.  It now runs, discovers my chrome cast, but the connection is refused.  Below is the output from terminal. Any help getting this working would be amazing - my aim is to stream all system audio to a group of chromecast audios.

Thanks :) 

```
pi@raspberrypi:~/mkchromecast $ python3 mkchromecast.py
mkchromecast v0.3.6
Creating pulseaudio sink...
Open pavucontrol and select the mkchromecast sink.
Starting local streaming server
[Done]
Selected backend: pared
Selected audio codec: mp3
Default bitrate used: 192k
Default sample rate used: 44100Hz
PID of main process: 4396
PID of streaming process: 4403
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 
List of Google Cast devices available in your network:
------------------------------------------------------
 
Index   Friendly name
=====   ============= 
0       Living Room
 
We will cast to first device in the list above!
 
Living Room
 
 
Information about  Living Room
 
DeviceStatus(friendly_name='Living Room', model_name='Chromecast Audio', manufacturer='Google Inc.', api_version=(1, 0), uuid=UUID('add8ae6c-37d1-f3cb-a782-48063b3d1f3c'), cast_type='audio')
 
Status of device  Living Room
 
CastStatus(is_active_input=None, is_stand_by=None, volume_level=0.08627451211214066, volume_muted=False, app_id=None, display_name=None, namespaces=[], session_id=None, transport_id=None, status_text='')
 
The IP of Living Room is: 192.168.0.19
Your local IP is: 192.168.0.13
 
The media type string used is: audio/mpeg
 
Cast media controller status
 
CastStatus(is_active_input=None, is_stand_by=None, volume_level=0.08627451211214066, volume_muted=False, app_id='CC1AD845', display_name='Default Media Receiver', namespaces=['urn:x-cast:com.google.cast.media', 'urn:x-cast:com.google.cast.inject'], session_id='67B2B0A1-234B-44C7-9DD1-7122BCBED072', transport_id='web-2', status_text='Ready To Cast')
 
Remember to open pavucontrol and select the mkchromecast sink.

Ctrl-C to kill the application at any time

[2016-10-04 14:49:37,565] ERROR in app: Exception on /stream [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.4/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pi/mkchromecast/mkchromecast/audio.py", line 520, in stream
    process = Popen(command, stdin=parec.stdout, stdout=PIPE, bufsize=-1)
  File "/usr/lib/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.4/subprocess.py", line 1457, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'lame'
192.168.0.19 - - [04/Oct/2016 14:49:37] "GET /stream HTTP/1.1" 500 -
```

**Comment by mattomatto** [comment]
I guess from the line `No such file or directory: 'lame'`
That it was the mp3 format being an issue, so I switched to wav and installed sox, and it works.
I do have lame installed though, which is strange.

**Comment by muammar** [comment]
@mattomatto I have just seen your report. Yes, lame was missing in your system. Are you using Debian or debian based distribution?. If yes, these are the dependencies:

https://packages.debian.org/unstable/mkchromecast

Glad you got it working.

**Comment by mattomatto** [comment]
Thanks for the reply mummer, I'm using Raspbian Jessie, so yes.  Thanks a lot for making awesome free stuff!!

**Comment by muammar** [comment]
@mattomatto thanks for your message :) Happy Casting!.
