### ISSUE TITLE
"encoding with idna codec failed" on Xubuntu 18.04

### ISSUE THREAD

**Issue by doucettom** [muammar/mkchromecast#228]
Crashes when I search for a Media Streaming device.

Selected backend: /usr/bin/parec
Selected audio codec: mp3
Default bitrate used: 192k
Default sample rate used: 44100Hz.
Traceback (most recent call last):
  File "/usr/share/mkchromecast/mkchromecast/cast.py", line 113, in _get_chromecasts
    return list(pychromecast.get_chromecasts_as_dict().keys())
AttributeError: module 'pychromecast' has no attribute 'get_chromecasts_as_dict'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/encodings/idna.py", line 167, in encode
    raise UnicodeError("label too long")
UnicodeError: label too long

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/share/mkchromecast/mkchromecast/tray_threading.py", line 47, in _search_cast_
    self.cc.initialize_cast()
  File "/usr/share/mkchromecast/mkchromecast/cast.py", line 135, in initialize_cast
    self.cclist = self._get_chromecasts()
  File "/usr/share/mkchromecast/mkchromecast/cast.py", line 117, in _get_chromecasts
    tries=self.tries)}
  File "/usr/lib/python3/dist-packages/pychromecast/__init__.py", line 81, in get_chromecasts
    blocking=blocking))
  File "/usr/lib/python3/dist-packages/pychromecast/__init__.py", line 48, in _get_chromecast_from_host
    blocking=blocking)
  File "/usr/lib/python3/dist-packages/pychromecast/__init__.py", line 142, in __init__
    dev_status = get_device_status(self.host)
  File "/usr/lib/python3/dist-packages/pychromecast/dial.py", line 49, in get_device_status
    timeout=10)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 520, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 630, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
UnicodeError: encoding with 'idna' codec failed (UnicodeError: label too long)

**Comment by muammar** [comment]
On Tue, Dec 18, 2018 at 11:21 AM doucettom <notifications@github.com> wrote:

> Crashes when I search for a Media Streaming device.
>
> Selected backend: /usr/bin/parec
> Selected audio codec: mp3
> Default bitrate used: 192k
> Default sample rate used: 44100Hz.
> Traceback (most recent call last):
> File "/usr/share/mkchromecast/mkchromecast/cast.py", line 113, in
> _get_chromecasts
> return list(pychromecast.get_chromecasts_as_dict().keys())
> AttributeError: module 'pychromecast' has no attribute
> 'get_chromecasts_as_dict'
>
>
>
What version of `pychromecast` is this?

-- 
Muammar El Khatib.
http://muammar.me

**Comment by doucettom** [comment]
0.8.1-1 (from ubuntu repo)

**Comment by greglondon** [comment]
Same issue here.
Xubuntu 20.10
pychromecast 7.1.1-1
