### ISSUE TITLE
Exception on /stream

### ISSUE THREAD

**Issue by tbl0605** [muammar/mkchromecast#230]
Hi,
I've downloaded latest master version of mkchromecast (december 27) and now when I'm doing:
`python3 /opt/mkchromecast-master/bin/mkchromecast --video --command 'ffmpeg -ac 2 -ar 44100 -frame_size 2048 -fragment_size 2048 -f pulse -ac 2 -i Mkchromecast.monitor -f x11grab -r 30 -s 1366x768 -i :0.0+0,0 -vcodec libx264 -preset veryfast -tune zerolatency -maxrate 10000k -bufsize 20000k -pix_fmt yuv420p -g 60 -f mp4 -movflags frag_keyframe+empty_moov -ar 44100 -acodec libvorbis pipe:1'`

I'm getting following error:
[2018-12-30 15:03:52,927] ERROR in app: Exception on /stream [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/mkchromecast-master/bin/../mkchromecast/video.py", line 318, in stream
    process = Popen(command, stdout=PIPE, bufsize=-1)
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1275, in _execute_child
    restore_signals, start_new_session, preexec_fn)
TypeError: expected str, bytes or os.PathLike object, not NoneType
192.168.31.76 - - [30/Dec/2018 15:03:52] "GET /stream HTTP/1.1" 500 -

It worked (and still working) nicely with master version from 14 october 2018.

Thank you for your help!
Thierry.

**Comment by muammar** [comment]
Thanks for reporting this! Can you let me know if it is fixed now by 8b52a42.

**Comment by tbl0605** [comment]
Yes thank you very much, it seems to fix the bug :)
Thank you for your great tool, it's much appreciated ;)
