### ISSUE TITLE
 data['applications'][0] IndexError: list index out of range

### ISSUE THREAD

**Issue by trydofor** [muammar/mkchromecast#273]
```
# uname -r
5.0.0-23-generic
# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
```

```
# mkchromecast --video -i "/home/trydofor/Videos/de.mp4"   

Mkchromecast v0.3.8.1
Starting Video Cast Process...
PID of main process: 16099
PID of streaming process: 16104
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 
List of Devices Available in Network:
-------------------------------------

Index   Types   Friendly Name 
=====   =====   ============= 
0 	Gcast 	MiraplusBF916818
 
Casting to first device shown above!
Select devices by using the -s flag.
 
MiraplusBF916818
 
ERROR:pychromecast.socket_client:Exception caught while sending message to controller ReceiverController: Message urn:x-cast:com.google.cast.receiver from receiver-0 to sender-0: {'requestId': 1, 'status': {'applications': [], 'isActiveInput': True, 'volume': {'controlType': 'attenuation', 'level': 1, 'muted': False, 'stepInterval': 0.05}}, 'type': 'RECEIVER_STATUS'}
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pychromecast/socket_client.py", line 456, in _route_message
    message, data)
  File "/usr/lib/python3/dist-packages/pychromecast/socket_client.py", line 769, in receive_message
    self._process_get_status(data)
  File "/usr/lib/python3/dist-packages/pychromecast/socket_client.py", line 900, in _process_get_status
    status = self._parse_status(data, self.cast_type)
  File "/usr/lib/python3/dist-packages/pychromecast/socket_client.py", line 878, in _parse_status
    app_data = data['applications'][0]
IndexError: list index out of range
```

**Comment by muammar** [comment]
On Sun, Aug 4, 2019 at 8:57 PM 史荣久 <notifications@github.com> wrote:

> # uname -r
> 5.0.0-23-generic
> # lsb_release -a
> No LSB modules are available.
> Distributor ID:	Ubuntu
> Description:	Ubuntu 18.04.2 LTS
> Release:	18.04
> Codename:	bionic
>
> # mkchromecast --video -i "/home/trydofor/Videos/de.mp4"
>
> Mkchromecast v0.3.8.1
> Starting Video Cast Process...
> PID of main process: 16099
> PID of streaming process: 16104
>  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
>
> List of Devices Available in Network:
> -------------------------------------
>
> Index   Types   Friendly Name
> =====   =====   =============
> 0 	Gcast 	MiraplusBF916818
>
> Casting to first device shown above!
> Select devices by using the -s flag.
>
> MiraplusBF916818
>
> ERROR:pychromecast.socket_client:Exception caught while sending message to controller ReceiverController: Message urn:x-cast:com.google.cast.receiver from receiver-0 to sender-0: {'requestId': 1, 'status': {'applications': [], 'isActiveInput': True, 'volume': {'controlType': 'attenuation', 'level': 1, 'muted': False, 'stepInterval': 0.05}}, 'type': 'RECEIVER_STATUS'}
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/pychromecast/socket_client.py", line 456, in _route_message
>     message, data)
>   File "/usr/lib/python3/dist-packages/pychromecast/socket_client.py", line 769, in receive_message
>     self._process_get_status(data)
>   File "/usr/lib/python3/dist-packages/pychromecast/socket_client.py", line 900, in _process_get_status
>     status = self._parse_status(data, self.cast_type)
>   File "/usr/lib/python3/dist-packages/pychromecast/socket_client.py", line 878, in _parse_status
>     app_data = data['applications'][0]
> IndexError: list index out of range
>
>
>
What version of pychromecast are you using?

-- 
Muammar El Khatib.
http://muammar.me

**Comment by 2vishnui** [comment]
Hi im also having same issue.
Im using anycast device and mkchromecast ( 0.3.8.1-1 ).

**Comment by MichaelRenner** [comment]
The same here. Also Ubuntu 18.04 LTS.
Does someone found a solution?
