### ISSUE TITLE
Can I get some help with this error?

### ISSUE THREAD

**Issue by SupernovaDML** [muammar/mkchromecast#281]
```
> ERROR:pychromecast.socket_client:Exception caught while sending message to controller ReceiverController: Message urn:x-cast:com.google.cast.receiver from receiver-0 to sender-0: {'requestId': 1, 'status': {'applications': [], 'isActiveInput': True, 'volume': {'controlType': 'attenuation', 'level': 1, 'muted': False, 'stepInterval': 0.05}}, 'type': 'RECEIVER_STATUS'}
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/pychromecast/socket_client.py", line 456, in _route_message
>     message, data)
>   File "/usr/lib/python3/dist-packages/pychromecast/socket_client.py", line 769, in receive_message
>     self._process_get_status(data)
>   File "/usr/lib/python3/dist-packages/pychromecast/socket_client.py", line 900, in _process_get_status
>     status = self._parse_status(data, self.cast_type)
>   File "/usr/lib/python3/dist-packages/pychromecast/socket_client.py", line 878, in _parse_status
>     app_data = data['applications'][0]
> IndexError: list index out of range
```

**Comment by bwduncan** [comment]
Duplicate of #273 ?
