### ISSUE TITLE
mkchromecast -t does not work

### ISSUE THREAD

**Issue by hedmo** [muammar/mkchromecast#284]
hi the mkchromecast -t command does not work here in gentoo 

`hedmo@mya51 ~ $ mkchromecast -t
Mkchromecast v0.3.9
Selected backend: /usr/bin/parec
Selected audio codec: mp3
Default bitrate used: 192k
Default sample rate used: 44100Hz.
Icon theme "Papirus-Dark" not found.
Icon theme "Yaru" not found.
Icon theme "Numix-Circle" not found.
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.6/mkchromecast", line 312, in <module>
    mk()
  File "/usr/lib/python-exec/python3.6/mkchromecast", line 66, in __init__
    self.start_tray()
  File "/usr/lib/python-exec/python3.6/mkchromecast", line 308, in start_tray
    mkchromecast.systray.main()
  File "/usr/lib64/python3.6/site-packages/mkchromecast/systray.py", line 863, in main
    menubar()
  File "/usr/lib64/python3.6/site-packages/mkchromecast/systray.py", line 158, in __init__
    self.createUI()
  File "/usr/lib64/python3.6/site-packages/mkchromecast/systray.py", line 163, in createUI
    self.ag = QtWidgets.QActionGroup(self, exclusive=True)
TypeError: 'exclusive' is an unknown keyword argument
hedmo@mya51 ~ $ 
`
otherwise it is working grate .good job getting chromecasts to work in linux

regards hedmo

**Comment by muammar** [comment]
Fixed.

**Comment by VitRuzicka** [comment]
I have the same issue, just compiled from AUR. How can I fix it?

**Comment by muammar** [comment]
I pushed a commit to `master` that solved the issue.

**Comment by jmgomezpoveda** [comment]
I seem to be having this same issue with version 0.3.8.1-1 (using Ubuntu 20.10).

**Comment by uteck** [comment]
Same with me on Ubuntu 18.04 and mkchromecstversion 0.3.8.1-1
`mkchromecast -t
Mkchromecast v0.3.8.1
Selected backend: /usr/bin/parec
Selected audio codec: mp3
Default bitrate used: 192k
Default sample rate used: 44100Hz.
Traceback (most recent call last):
  File "/usr/bin/mkchromecast", line 283, in <module>
    mk()
  File "/usr/bin/mkchromecast", line 59, in __init__
    self.start_tray()
  File "/usr/bin/mkchromecast", line 280, in start_tray
    mkchromecast.systray.main()
  File "/usr/share/mkchromecast/mkchromecast/systray.py", line 900, in main
    menubar()
  File "/usr/share/mkchromecast/mkchromecast/systray.py", line 164, in __init__
    self.createUI()
  File "/usr/share/mkchromecast/mkchromecast/systray.py", line 169, in createUI
    self.ag = QtWidgets.QActionGroup(self, exclusive=True)
TypeError: 'exclusive' is an unknown keyword argument
`

**Comment by BlackHawk185** [comment]
Same
`user@user-pc ~ $ mkchromecast -t
Mkchromecast v0.3.8.1
Selected backend: /usr/bin/parec
Selected audio codec: mp3
Default bitrate used: 192k
Default sample rate used: 44100Hz.
Traceback (most recent call last):
  File "/usr/bin/mkchromecast", line 283, in <module>
    mk()
  File "/usr/bin/mkchromecast", line 59, in __init__
    self.start_tray()
  File "/usr/bin/mkchromecast", line 280, in start_tray
    mkchromecast.systray.main()
  File "/usr/share/mkchromecast/mkchromecast/systray.py", line 900, in main
    menubar()
  File "/usr/share/mkchromecast/mkchromecast/systray.py", line 164, in __init__
    self.createUI()
  File "/usr/share/mkchromecast/mkchromecast/systray.py", line 169, in createUI
    self.ag = QtWidgets.QActionGroup(self, exclusive=True)
TypeError: 'exclusive' is an unknown keyword argument
`

**Comment by bschelst** [comment]
same on kde neon 20.04 (ubuntu  20.04)..

**Comment by AJV009** [comment]
I navigated to the file and removed "exclusive" and ran again, it was fixed but I still face someother bug now!

**Comment by lyctw** [comment]
same issue 

```
mkchromecast -t                                                                                                                                                        ─╯
/usr/share/mkchromecast/mkchromecast/cast.py:111: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if iface is not None and iface[0]['addr'] is not '127.0.0.1':
Mkchromecast v0.3.8.1
/usr/share/mkchromecast/mkchromecast/systray.py:797: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if platform is 'Darwin':
/usr/share/mkchromecast/mkchromecast/systray.py:803: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if platform is 'Linux':
/usr/share/mkchromecast/mkchromecast/systray.py:864: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if platform is 'Darwin' and self.notifications is 'enabled':
/usr/share/mkchromecast/mkchromecast/systray.py:864: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if platform is 'Darwin' and self.notifications is 'enabled':
Selected backend: /usr/bin/parec
Selected audio codec: mp3
Default bitrate used: 192k
Default sample rate used: 44100Hz.
Traceback (most recent call last):
  File "/usr/bin/mkchromecast", line 283, in <module>
    mk()
  File "/usr/bin/mkchromecast", line 59, in __init__
    self.start_tray()
  File "/usr/bin/mkchromecast", line 280, in start_tray
    mkchromecast.systray.main()
  File "/usr/share/mkchromecast/mkchromecast/systray.py", line 910, in main
    menubar()
  File "/usr/share/mkchromecast/mkchromecast/systray.py", line 173, in __init__
    self.createUI()
  File "/usr/share/mkchromecast/mkchromecast/systray.py", line 178, in createUI
    self.ag = QtWidgets.QActionGroup(self, exclusive=True)
TypeError: 'exclusive' is an unknown keyword argument
```
