### ISSUE TITLE
(Linux) SyntaxWarning: "is not" with a literal. Did you mean "!="?

### ISSUE THREAD

**Issue by lodovicoset** [muammar/mkchromecast#286]
This error just pop up today, cannot connect to any device. Seems to be something related with Python. Suing Void Linux

[lodovico@void ~]$ mkchromecast -c flac
/usr/share/mkchromecast/mkchromecast/cast.py:103: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if iface is not None and iface[0]['addr'] is not '127.0.0.1':
Mkchromecast v0.3.8.1
Creating Pulseaudio Sink...
Open Pavucontrol and Select the Mkchromecast Sink.
Starting Local Streaming Server
[Done]
Selected backend: parec
Selected audio codec: flac
Default bitrate used: 192k
Default sample rate used: 44100Hz.
Traceback (most recent call last):
  File "/bin/mkchromecast", line 283, in <module>
    mk()
  File "/bin/mkchromecast", line 53, in __init__
    self.audio_linux()
  File "/bin/mkchromecast", line 71, in audio_linux
    self.start_backend(self.encoder_backend)
  File "/bin/mkchromecast", line 158, in start_backend
    import mkchromecast.audio
  File "/usr/share/mkchromecast/mkchromecast/audio.py", line 711, in <module>
    app = Flask(__name__)
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 601, in __init__
    self.add_url_rule(
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 98, in wrapper_func
    return f(self, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1277, in add_url_rule
    self.url_map.add(rule)
  File "/usr/lib/python3.8/site-packages/werkzeug/routing.py", line 1388, in add
    rule.bind(self)
  File "/usr/lib/python3.8/site-packages/werkzeug/routing.py", line 730, in bind
    self.compile()
  File "/usr/lib/python3.8/site-packages/werkzeug/routing.py", line 794, in compile
    self._build = self._compile_builder(False).__get__(self, None)
  File "/usr/lib/python3.8/site-packages/werkzeug/routing.py", line 951, in _compile_builder
    code = compile(module, "<werkzeug routing>", "exec")
TypeError: required field "type_ignores" missing from Module

**Comment by Pavlos1** [comment]
The error here is not the syntax _warning_ at the start, it is the type _error_ at the end:
```
TypeError: required field "type_ignores" missing from Module
```
FWIW: it seems that the line causing the warning has moved [here](https://github.com/muammar/mkchromecast/blob/4112dead95f8acfd6a63d4a8787fa8c1ed7f54f3/mkchromecast/utils.py#L158). I agree with the Python interpreter that this line is not correct, but it is not (directly) causing your error.

Unfortunately I'm not familiar with this codebase so I don't know under what conditions I would be able to replicate the issue. I tried running `mkchromecast -c flac` on the latest version and did not get any errors.

**Comment by lodovicoset** [comment]
Very kind of you Pavel. I'm still struggling with this issue. Seems something to do with zeroconf after an update. I've asked for help in https://www.reddit.com/r/voidlinux/
