### ISSUE TITLE
Ubuntu 20.04 (package + current master) breaks because of pychromecast

### ISSUE THREAD

**Issue by stucki** [muammar/mkchromecast#302]
Just upgraded my system to Ubuntu 20.04 (still beta, but soon to be released). When trying to play a radio stream, nothing happens on my Nest Hub:

```
$  mkchromecast --name "Google Nest Hub" --notifications --source-url <url>
Mkchromecast v0.3.8.1
[record[a,in-unique,...1234.local.]=120/119,192.168.1.179:8009] Failed to connect, retrying in 5.0s
```

I also tried to run the latest master version of this project with the same result.

It turns out that pychromecast 4.1.0 which is shipped in Ubuntu 20.04 is buggy. After updating requirements.txt to load `pychromecast>=4.2`, it installs version `4.2.3`. Now the package version as well as current master are working fine again.

(I'm aware that this is probably a bug in Ubuntu 20.04 who should update their shipped pychromecast version, but still wanted to have it documented here.)

see also #297

**Comment by wyvernwaddell** [comment]
Steps to update to pychromecast>=4.2  please?

**Comment by stucki** [comment]
`pip3 install "pychromecast>=4.2"`

**Comment by wyvernwaddell** [comment]
Thank you :)

**Comment by stucki** [comment]
Finally reported this issue to Ubuntu: https://bugs.launchpad.net/ubuntu/+source/pychromecast/+bug/1875688

**Comment by psteckler** [comment]
> `pip3 install "pychromecast>=4.2"`

That didn't work for me, but `pip3 install "pychromecast==4.2"` did.

**Comment by ghomem** [comment]
I confirm that what works on 20.04 is

```
pip3 install "pychromecast==4.2"
```

**Comment by ricosaurus** [comment]
Similar issue for me, but install of pychromecast==4.2 has not resolved:

USER@mycomputer:~$ mkchromecast --select
Mkchromecast v0.3.8.1
Creating Pulseaudio Sink...
Open Pavucontrol and Select the Mkchromecast Sink.
Starting Local Streaming Server
[Done]
Selected backend: parec
Selected audio codec: mp3
Default bitrate used: 192k
Default sample rate used: 44100Hz.
PID of main process: 4004
PID of streaming process: 4081
 * Serving Flask app "mkchromecast.audio" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 
List of Devices Available in Network:
-------------------------------------

Index   Types   Friendly Name 
=====   =====   ============= 
0 	Gcast 	Kitchen speaker
1 	Gcast 	Upstairs Bedroom display
2 	Gcast 	Upstairs Bedroom speaker
3 	Gcast 	Dining Room speaker
4 	Gcast 	Bedroom speaker
 
Please, select the Index of the Google Cast device that you want to use:
2
 
Casting to: Upstairs Bedroom speaker
 
[record[a,in-unique,602080ac-3141-3f34-fd3c-4fabfbbdc692.local.]=120/119,192.168.0.71:8009] Failed to connect, retrying in 5.0s

**Comment by Dropsik** [comment]
After 
`pip3 install "pychromecast==4.2"`

I have error:
`mkchromecast -t                 
Traceback (most recent call last):
  File "/usr/bin/mkchromecast", line 8, in <module>
    from mkchromecast.cast import *
  File "/usr/share/mkchromecast/mkchromecast/cast.py", line 14, in <module>
    from pychromecast.dial import reboot
ImportError: cannot import name 'reboot' from 'pychromecast.dial' (/usr/local/lib/python3.8/dist-packages/pychromecast/dial.py)
`

**Comment by Philipp91** [comment]
> `cannot import name 'reboot' from 'pychromecast.dial'`

`sudo pip3 install pychromecast==4.1.1` (from https://github.com/muammar/mkchromecast/issues/366#issuecomment-873084543).

**Comment by raquelhortab** [comment]
Still not working for me... It also stopped working after upgrading to ubuntu 20

```
Mkchromecast v0.3.8.1
Starting Video Cast Process...
PID of main process: 21181
PID of streaming process: 21184
 * Serving Flask app "mkchromecast.video" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 
List of Devices Available in Network:
-------------------------------------

Index   Types   Friendly Name 
=====   =====   ============= 
0 	Gcast 	KD-55XE8096
 
Casting to first device shown above!
Select devices by using the -s flag.
 
KD-55XE8096
 
[192.168.100.15:8009] Failed to connect, retrying in 5.0s

```

No error is shown so I have no idea what is wrong
