### ISSUE TITLE
selection of sonos device not working with -s or -n

### ISSUE THREAD

**Issue by LouBerry** [muammar/mkchromecast#309]
Hi all,

overall mkchromecast is working on manjaro, installed from aur with soco to stream to sonso.
just issuing the command 

`mkchromecast` 

It randomly broadcasts to the first device found.

But when I want to specify the device I get an error, which seems to be python related.
This is the output: 

```
$ mkchromecast -s
Mkchromecast v0.3.9
Creating Pulseaudio Sink...
Open Pavucontrol and Select the Mkchromecast Sink.
Starting Local Streaming Server
[Done]
Selected backend: parec
Selected audio codec: mp3
Default bitrate used: 192k
Default sample rate used: 44100Hz.
PID of main process: 8477
PID of streaming process: 8483
 * Serving Flask app "mkchromecast.audio" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://192.168.178.25:5000/ (Press CTRL+C to quit)
 
List of Devices Available in Network:
-------------------------------------

Index   Types   Friendly Name 
=====   =====   ============= 
0       Gcast   KD-55XE9005
1       Sonos   Living Room
2       Sonos   Bedroom
3       Sonos   Kitchen
4       Sonos   Lounge
 
Please, select the Index of the Google Cast device that you want to use:
4
 
Casting to: Lounge
The IP of Lounge is: 192.168.178.31
Your local IP is: 192.168.178.25
Traceback (most recent call last):
  File "./bin/../mkchromecast/cast.py", line 330, in play_cast
    media_controller = self.cast.media_controller
AttributeError: 'Casting' object has no attribute 'cast'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./bin/mkchromecast", line 312, in <module>
    mk()
  File "./bin/mkchromecast", line 60, in __init__
    self.audio_linux()
  File "./bin/mkchromecast", line 81, in audio_linux
    self.cc.play_cast()
  File "./bin/../mkchromecast/cast.py", line 409, in play_cast
    self.sonos.play_uri(
  File "/home/lou/.local/lib/python3.8/site-packages/soco/core.py", line 104, in inner_function
    raise SoCoSlaveException(message)
soco.exceptions.SoCoSlaveException: The method or property "play_uri" can only be called/used on the coordinator in a group

```

**Comment by muammar** [comment]
The error that you describe here happens when you have created a Sonos Group. In this case, the `Lounge` device cannot be used with the method `play_uri`. I am investigating this. For the time being, try with other speakers in the group that `Lounge` is part of, and that should work.

**Comment by LouBerry** [comment]
Finally had time to test it and after ungrouping the speaker it works fine. Thanks :)
Keep on the greate work!
