### ISSUE TITLE
Mkcrhomecast crashes after installing in Manjaro using yay

### ISSUE THREAD

**Issue by cprpolo** [muammar/mkchromecast#336]
When launching it crashes straight away with Devices not found:
`mkchromecast 
Mkchromecast v0.3.8.1
Creating Pulseaudio Sink...
Open Pavucontrol and Select the Mkchromecast Sink.
Starting Local Streaming Server
[Done]
Selected backend: parec
Selected audio codec: mp3
Default bitrate used: 192k
Default sample rate used: 44100Hz.
No devices found!
 * Serving Flask app "mkchromecast.audio" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
PID of main process: 32780
   Use a production WSGI server instead.
PID of streaming process: 32789
 * Debug mode: off
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
Cleaning up /tmp/...
[Done]
Killed
`
tried with debug:
`mkchromecast --debug -t
ALSA device name: None.
Google Cast name: None.
backends:  ['ffmpeg', 'avconv', 'parec', 'gstreamer']
ALSA device name: None.
Google Cast name: None.
backends:  ['ffmpeg', 'avconv', 'parec', 'gstreamer']
USER =username
PATH =/home/username/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/var/lib/snapd/snap/bin
Mkchromecast v0.3.8.1
:::cast::: sockets method 192.168.178.20
/usr/share/mkchromecast/mkchromecast/systray.py:797: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if platform is 'Darwin':
/usr/share/mkchromecast/mkchromecast/systray.py:803: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if platform is 'Linux':
/usr/share/mkchromecast/mkchromecast/systray.py:864: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if platform is 'Darwin' and self.notifications is 'enabled':
/usr/share/mkchromecast/mkchromecast/systray.py:864: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if platform is 'Darwin' and self.notifications is 'enabled':
:::audio::: chunk_size, frame_size, buffer_size: 64, 2048, 8192
:::audio::: Program /usr/bin/parec found in /usr/bin/parec
:::audio::: backend dictionary {'parec': 'parec', '/usr/bin/parec': 'parec'}
Selected backend: /usr/bin/parec
Selected audio codec: mp3
Default bitrate used: 192k
Default sample rate used: 44100Hz.
:::audio::: command ['lame', '-b', '192', '-r', '-']
:::cast::: sockets method 192.168.178.20
:::systray::: self.notifications disabled
:::systray::: self.searchatlaunch disabled
:::systray::: self.colors black
:::systray::: Screen resolution:  1920 1080
:::systray::: High-DPI screen detected...
Traceback (most recent call last):
  File "/usr/bin/mkchromecast", line 283, in <module>
    mk()
  File "/usr/bin/mkchromecast", line 59, in __init__
    self.start_tray()
  File "/usr/bin/mkchromecast", line 280, in start_tray
    mkchromecast.systray.main()
  File "/usr/share/mkchromecast/mkchromecast/systray.py", line 910, in main
    menubar()
  File "/usr/share/mkchromecast/mkchromecast/systray.py", line 173, in __init__
    self.createUI()
  File "/usr/share/mkchromecast/mkchromecast/systray.py", line 178, in createUI
    self.ag = QtWidgets.QActionGroup(self, exclusive=True)
TypeError: 'exclusive' is an unknown keyword argument
`

**Comment by caiges** [comment]
Can confirm this as well.

**Comment by ShawnMcCool** [comment]
I solved this by running `yay -S pulseaudio-dlna` and selecting the third option "pulseaudio-dlna-python3-git".

**Comment by BerenLuth** [comment]
Same exact error here.
When I tried to install ```pulseaudio-dlna``` it showed only two options and no ```-python3-git``` option, I tried to install one of the other versions anyway but unfortunately it didn't fix the problem.

**Comment by diegomachadosoares** [comment]
Hi, guys.

Had the exact same problem on Archlinux.
As @BerenLuth said, when looking for `pulseaudio-dlna` (also using yay),  only two options appear and none of them had `-python3-git`.
But for me it fixed installing the first option which is just `pulseaudio-dlna`.

Hope it helps!

**Comment by vannaka** [comment]
This is a duplicate of issue: https://github.com/muammar/mkchromecast/issues/29. See that issue for another fix, the one here didn't work for me.

**Comment by chaorace** [comment]
Installing `pulseaudio-dlna` via AUR also resolved the issue for me on Manjaro.
