### ISSUE TITLE
ImportError: cannot import name 'reboot'

### ISSUE THREAD

**Issue by DolleDries** [muammar/mkchromecast#339]
python3
Python 3.6.9 (default, Oct  8 2020, 12:12:24) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pychromecast
>>> from pychromecast.dial import reboot
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'reboot'
>>> 

mkchromecast_0.3.8.1-1_all.deb
Ubuntu 18.04.5 LTS

**Comment by santiagozky** [comment]
having the same issue. I would assume this is the problem: https://github.com/home-assistant-libs/pychromecast/pull/394
the "reboot" function was removed from pychromecast

**Comment by DolleDries** [comment]
Removed import... Error gone. Close?

**Comment by ander7agar** [comment]
Same issue on Ubuntu 20.04 LTS. Installed from Snap store.

**Comment by romanmatyus** [comment]
Same problem :/

**Comment by improvethings** [comment]
Idem.

$ lsb_release -d
Description:	Pop!_OS 20.10
$ uname -srm
Linux 5.11.0-7614-generic x86_64
$ dpkg -l | grep mkchr
ii  mkchromecast                                     0.3.8.1-1

**Comment by jergas** [comment]
same issue.
I had installed it from the Debian package manager (I'm running Siduction), and used it over a year ago. 
Right now I upgraded the package, but then installed the .deb from the main page (https://github.com/muammar/mkchromecast/releases/download/0.3.8.1/mkchromecast_0.3.8.1-1_all.deb), as I understood it was necessary in order to use the system tray widget.
here is my traceback:
$ mkchromecast 
Traceback (most recent call last):
  File "/usr/bin/mkchromecast", line 8, in <module>
    from mkchromecast.cast import *
  File "/usr/share/mkchromecast/mkchromecast/cast.py", line 14, in <module>
    from pychromecast.dial import reboot
ImportError: cannot import name 'reboot' from 'pychromecast.dial' (/usr/lib/python3/dist-packages/pychromecast/dial.py)

**Comment by jergas** [comment]
PS: I just reinstalled the one that comes with the package manager, and now it works.
This is the package that was installed by aptitude:
mkchromecast_0.3.9~git20200902+db2964a-2_all.deb

**Comment by Ben1701A** [comment]
Broken here. Used `mkchromecast_0.3.8.1-1_all.deb` from the main site and converted with `alien` to install via dnf on my Fedora system.
`pychromecast` wasn't installed with it, so I installed that via pip3.
```
$ mkchromecast
/usr/share/mkchromecast/mkchromecast/cast.py:103: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if iface is not None and iface[0]['addr'] is not '127.0.0.1':
Traceback (most recent call last):
  File "/usr/bin/mkchromecast", line 8, in <module>
    from mkchromecast.cast import *
  File "/usr/share/mkchromecast/mkchromecast/cast.py", line 14, in <module>
    from pychromecast.dial import reboot
ImportError: cannot import name 'reboot' from 'pychromecast.dial' (~/.local/lib/python3.10/site-packages/pychromecast/dial.py)
```
Searching for 'reboot' in dial.py yields nothing. However, I looked into an older version (sayyy 7.1.0, pulled source from home-assistant-libs/pychromecast) and the reboot definition shows up.

The reboot feature may have been dropped.

**Comment by Ben1701A** [comment]
After adding the 'reboot' definition back in, I ran into another weird problem:

```
Mkchromecast v0.3.8.1
Creating Pulseaudio Sink...
Open Pavucontrol and Select the Mkchromecast Sink.
Starting Local Streaming Server
[Done]
Selected backend: parec
Selected audio codec: mp3
Default bitrate used: 192k
Default sample rate used: 44100Hz.
PID of main process: 7437
 * Serving Flask app 'mkchromecast.audio' (lazy loading)
PID of streaming process: 7442
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://[snip!]:5000 (Press CTRL+C to quit)
Traceback (most recent call last):
  File "/usr/share/mkchromecast/mkchromecast/cast.py", line 113, in _get_chromecasts
    return list(pychromecast.get_chromecasts_as_dict().keys())
AttributeError: module 'pychromecast' has no attribute 'get_chromecasts_as_dict'. Did you mean: 'get_chromecast_from_host'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/mkchromecast", line 283, in <module>
    mk()
  File "/usr/bin/mkchromecast", line 53, in __init__
    self.audio_linux()
  File "/usr/bin/mkchromecast", line 72, in audio_linux
    self.cc.initialize_cast()
  File "/usr/share/mkchromecast/mkchromecast/cast.py", line 135, in initialize_cast
    self.cclist = self._get_chromecasts()
  File "/usr/share/mkchromecast/mkchromecast/cast.py", line 115, in _get_chromecasts
    self._chromecasts_by_name = {c.name: c for c in
  File "/usr/share/mkchromecast/mkchromecast/cast.py", line 115, in <dictcomp>
    self._chromecasts_by_name = {c.name: c for c in
AttributeError: 'list' object has no attribute 'name'
```

I get the feeling the version of pychromecast this project depends on is outdated...

**Comment by xianwenchen** [comment]
Same issue on Void Linux.

**Comment by reques6e** [comment]
<img width="1223" height="683" alt="Image" src="https://github.com/user-attachments/assets/6a3a8c78-2e36-4573-bf3f-48113059664e" />
