### ISSUE TITLE
OSError: [Errno 105] No buffer space available

### ISSUE THREAD

**Issue by DolleDries** [muammar/mkchromecast#340]
Ubuntu 18.04.5 LTS
Mkchromecast v0.3.9
Creating Pulseaudio Sink...
Open Pavucontrol and Select the Mkchromecast Sink.
Starting Local Streaming Server
[Done]
Selected backend: parec
Selected audio codec: mp3
Default bitrate used: 192k
Default sample rate used: 44100Hz.
 * Serving Flask app "mkchromecast.audio" (lazy loading)
PID of main process: 1896
 * Environment: production
PID of streaming process: 1907
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://192.168.178.55:5000/ (Press CTRL+C to quit)
Traceback (most recent call last):
  File "bin/mkchromecast", line 311, in <module>
    mk()
  File "bin/mkchromecast", line 59, in __init__
    self.audio_linux()
  File "bin/mkchromecast", line 78, in audio_linux
    self.cc.initialize_cast()
  File "/home/andre/Speeltuin/mkchromecast/bin/../mkchromecast/cast.py", line 110, in initialize_cast
    self.cclist = self._get_chromecasts()
  File "/home/andre/Speeltuin/mkchromecast/bin/../mkchromecast/cast.py", line 81, in _get_chromecasts
    _chromecasts = pychromecast.get_chromecasts(tries=self.tries)
  File "/usr/local/lib/python3.6/dist-packages/pychromecast/__init__.py", line 218, in get_chromecasts
    services, browser = discover_chromecasts()
  File "/usr/local/lib/python3.6/dist-packages/pychromecast/discovery.py", line 184, in discover_chromecasts
    zconf = zeroconf_instance or zeroconf.Zeroconf()
  File "/usr/local/lib/python3.6/dist-packages/zeroconf/__init__.py", line 2395, in __init__
    interfaces, unicast, ip_version, apple_p2p=apple_p2p
  File "/usr/local/lib/python3.6/dist-packages/zeroconf/__init__.py", line 2319, in create_sockets
    respond_socket = add_multicast_member(cast(socket.socket, listen_socket), i, apple_p2p=apple_p2p)
  File "/usr/local/lib/python3.6/dist-packages/zeroconf/__init__.py", line 2264, in add_multicast_member
    listen_socket.setsockopt(socket.IPPROTO_IP, socket.IP_ADD_MEMBERSHIP, _value)
OSError: [Errno 105] No buffer space available

respond_socket = add_multicast_member(cast(socket.socket, listen_socket), i, apple_p2p=apple_p2p)?
apple_p2p??? in zeroconf???

**Comment by DolleDries** [comment]
This helped:

Update the net/ipv4/igmp_max_memberships value of sysctl to greater than zero. Execute the following commands on the terminal: $ systctl -w net.ipv4.igmp_max_memberships=20 (or any other value greater than zero) & $ sysctl -w net.ipv4.igmp_max_msf=10

Then, restart the avahi-daemon systemctl restart avahi-daemon
