### ISSUE TITLE
Fails to connect to device - ubuntu 20.04

### ISSUE THREAD

**Issue by lex1000** [muammar/mkchromecast#342]
Fails to connect to any device (running on ubuntu 20.04, Python 3.8.5) with the following error:

 #033[0m#033[33m:::Threading::: Configuration file exists.#033[0m
 #033[0m#033[33m:::Threading::: Using defaults set there.#033[0m
 :::Threading backend::: parec.
 #033[0m#033[04mSelected backend:#033[0m /usr/bin/parec
 #033[0m#033[04mSelected audio codec:#033[0m mp3
 #033[0m#033[04mDefault bitrate used:#033[0m 192k
 #033[0m#033[04mDefault sample rate used:#033[0m 44100Hz.
  * Serving Flask app "mkchromecast.audio" (lazy loading)
  * Environment: production
 #033[0m#033[04mPID of main process:#033[0m 22224
 #033[0m#033[04mPID of streaming process:#033[0m 22248
    WARNING: This is a development server. Do not use it in a production deployment.
    Use a production WSGI server instead.
  * Debug mode: off
  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 Traceback (most recent call last):
   File "/usr/share/mkchromecast/mkchromecast/systray.py", line 547, in stop_cast
     self.cast.quit_app()
 AttributeError: 'NoneType' object has no attribute 'quit_app'
 During handling of the above exception, another exception occurred:
 Traceback (most recent call last):
   File "/usr/share/mkchromecast/mkchromecast/systray.py", line 517, in pcastready
     self.stop_cast()
   File "/usr/share/mkchromecast/mkchromecast/systray.py", line 551, in stop_cast
     self.cast.stop()
 AttributeError: 'NoneType' object has no attribute 'stop'

**Comment by ghomem** [comment]
related #302
