### ISSUE TITLE
TypeError: 'exclusive' is an unknown keyword argument

### ISSUE THREAD

**Issue by devmrfitz** [muammar/mkchromecast#352]
mkchromecast installed from aur using yay

`~$ mkchromecast -t
/usr/share/mkchromecast/mkchromecast/cast.py:111: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if iface is not None and iface[0]['addr'] is not '127.0.0.1':
Mkchromecast v0.3.8.1
/usr/share/mkchromecast/mkchromecast/systray.py:797: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if platform is 'Darwin':
/usr/share/mkchromecast/mkchromecast/systray.py:803: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if platform is 'Linux':
/usr/share/mkchromecast/mkchromecast/systray.py:864: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if platform is 'Darwin' and self.notifications is 'enabled':
/usr/share/mkchromecast/mkchromecast/systray.py:864: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if platform is 'Darwin' and self.notifications is 'enabled':
Selected backend: /usr/bin/parec
Selected audio codec: mp3
Default bitrate used: 192k
Default sample rate used: 44100Hz.
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
QSocketNotifier: Can only be used with threads started with QThread
Traceback (most recent call last):
  File "/usr/bin/mkchromecast", line 283, in <module>
    mk()
  File "/usr/bin/mkchromecast", line 59, in __init__
    self.start_tray()
  File "/usr/bin/mkchromecast", line 280, in start_tray
    mkchromecast.systray.main()
  File "/usr/share/mkchromecast/mkchromecast/systray.py", line 910, in main
    menubar()
  File "/usr/share/mkchromecast/mkchromecast/systray.py", line 173, in __init__
    self.createUI()
  File "/usr/share/mkchromecast/mkchromecast/systray.py", line 178, in createUI
    self.ag = QtWidgets.QActionGroup(self, exclusive=True)
TypeError: 'exclusive' is an unknown keyword argument
`

**Comment by devcomputer** [comment]
same. Pop OS 20 apt install mkchromecast

> $ mkchromecast -t
> Mkchromecast v0.3.8.1
> Selected backend: /usr/bin/parec
> Selected audio codec: mp3
> Default bitrate used: 192k
> Default sample rate used: 44100Hz.
> Traceback (most recent call last):
>   File "/usr/bin/mkchromecast", line 283, in <module>
>     mk()
>   File "/usr/bin/mkchromecast", line 59, in __init__
>     self.start_tray()
>   File "/usr/bin/mkchromecast", line 280, in start_tray
>     mkchromecast.systray.main()
>   File "/usr/share/mkchromecast/mkchromecast/systray.py", line 900, in main
>     menubar()
>   File "/usr/share/mkchromecast/mkchromecast/systray.py", line 164, in __init__
>     self.createUI()
>   File "/usr/share/mkchromecast/mkchromecast/systray.py", line 169, in createUI
>     self.ag = QtWidgets.QActionGroup(self, exclusive=True)
> **TypeError: 'exclusive' is an unknown keyword argument**

**Comment by hughwilliams94** [comment]
Removing `exclusive=True` seems to work fine

**Comment by hughwilliams94** [comment]
In fact I think this is already fixed in the master branch as the `mkchromecast-git` aur package works fine.

**Comment by BrunoSpy** [comment]
0.3.8.1 is 4 years old now, maybe it's time to release a new version ?
