### ISSUE TITLE
Tray app cannot select device

### ISSUE THREAD

**Issue by koenlavooij** [muammar/mkchromecast#367]
When I use `mkchromecast` from the terminal everything works as expected.

When I use `mkchromcast -t` and select my device it fails:

Before selecting a device (expected output, I guess)
```
::Threading::: Configuration file exists.
:::Threading::: Using defaults set there.
:::Threading backend::: parec.
Selected backend: /usr/bin/parec
Selected audio codec: mp3
Default bitrate used: 192k
Default sample rate used: 44100Hz.
PID of main process: 335452
PID of streaming process: 335490
 * Serving Flask app "mkchromecast.audio" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://192.168.1.100:5000/ (Press CTRL+C to quit)
List of Devices Available in Network:
-------------------------------------

Index   Types   Friendly Name 
=====   =====   ============= 
0 	Sonos 	Huiskamer
```

After selecting my device (Sonos):
```
Casting to: Huiskamer


pcastready ? _play_cast_ failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/mkchromecast/systray.py", line 508, in stop_cast
    self.cast.quit_app()
AttributeError: 'NoneType' object has no attribute 'quit_app'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/mkchromecast/systray.py", line 479, in pcastready
    self.stop_cast()
  File "/usr/lib/python3/dist-packages/mkchromecast/systray.py", line 512, in stop_cast
    self.cast.stop()
AttributeError: 'NoneType' object has no attribute 'stop'
```

**Comment by george1955** [comment]
I use Zorin OS and it works flawlessly. As an experiment I tried on both Pop OS and Linux Mint. Both had similar errors to you and would not cast to my Sonos device from the Tray app. I had to use the Terminal and mkchromecast -s for it to work. 
Zorin uses Gnome2 Desktop.

**Comment by timgilbert** [comment]
I got the same error (running Gnome on Manjaro). The suggestion to use `mkchromecast -s` worked for me. (Turned out the lag was too bad to be usable for me, sadly)

**Comment by tosanen** [comment]
Running pop-os 22.04, so typed following for a explanation of mkchromcast:
$ mkchromcast -h

Then I typed following to choose my device or devices:
$ mkchromecast --select-device

type number of device
hit return
