### ISSUE TITLE
pychromecast.error.NotConnected: Chromecast x.x.x.x:8009 is connecting...

### ISSUE THREAD

**Issue by caleballen** [muammar/mkchromecast#379]
```Mkchromecast v0.3.9
Creating Pulseaudio Sink...
Open Pavucontrol and Select the Mkchromecast Sink.
Starting Local Streaming Server
[Done]
Selected backend: parec
Selected audio codec: mp3
Default bitrate used: 192k
Default sample rate used: 44100Hz.
 * Serving Flask app 'mkchromecast.audio' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
PID of main process: 334869
 * Debug mode: off
PID of streaming process: 334873
 * Running on http://192.168.0.11:5000/ (Press CTRL+C to quit)
 
List of Devices Available in Network:
-------------------------------------

Index   Types   Friendly Name 
=====   =====   ============= 
0 	Gcast 	Caleb's Google Nest
 
Casting to first device shown above!
Select devices by using the -s flag.
 
Caleb's Google Nest
 
The IP of Caleb's Google Nest is: 192.168.0.14
Your local IP is: 192.168.0.11
 
The media type string used is: audio/mpeg
Traceback (most recent call last):
  File "/home/caleb/Applications/mkchromecast/bin/mkchromecast", line 311, in <module>
    mk()
  File "/home/caleb/Applications/mkchromecast/bin/mkchromecast", line 59, in __init__
    self.audio_linux()
  File "/home/caleb/Applications/mkchromecast/bin/mkchromecast", line 80, in audio_linux
    self.cc.play_cast()
  File "/home/caleb/Applications/mkchromecast/bin/../mkchromecast/cast.py", line 394, in play_cast
    media_controller.play_media(
  File "/usr/lib/python3.9/site-packages/pychromecast/controllers/media.py", line 546, in play_media
    receiver_ctrl.launch_app(self.app_id, callback_function=app_launched_callback)
  File "/usr/lib/python3.9/site-packages/pychromecast/socket_client.py", line 1126, in launch_app
    self.update_status(
  File "/usr/lib/python3.9/site-packages/pychromecast/socket_client.py", line 1115, in update_status
    self.send_message(
  File "/usr/lib/python3.9/site-packages/pychromecast/controllers/__init__.py", line 90, in send_message
    self.send_message_nocheck(data, inc_session_id, callback_function)
  File "/usr/lib/python3.9/site-packages/pychromecast/controllers/__init__.py", line 94, in send_message_nocheck
    self._message_func(self.namespace, data, inc_session_id, callback_function)
  File "/usr/lib/python3.9/site-packages/pychromecast/socket_client.py", line 891, in send_platform_message
    return self.send_message(
  File "/usr/lib/python3.9/site-packages/pychromecast/socket_client.py", line 829, in send_message
    self._ensure_channel_connected(destination_id)
  File "/usr/lib/python3.9/site-packages/pychromecast/socket_client.py", line 929, in _ensure_channel_connected
    self.send_message(
  File "/usr/lib/python3.9/site-packages/pychromecast/socket_client.py", line 883, in send_message
    raise NotConnected(
pychromecast.error.NotConnected: Chromecast 192.168.0.14:8009 is connecting...```

I've installed from AUR and I've tried the GitHub version. Have tried multiple versions of packages. Any ideas?

**Comment by jaimiewashere** [comment]
I'm having the same problem!
though, this looks like an issue with pychromecast 🤔

**Comment by jaimiewashere** [comment]
aah, found something: https://github.com/home-assistant-libs/pychromecast/issues/274#issuecomment-471869146
Seems like it's a quirk with pychomecast 3.0, i'll try to see if I can find a workaround on my end..

**Comment by jaimiewashere** [comment]
Using source & pip instead of my system's package manager works for me 👍🏼
Can you please check if that's the case with your system too?

**Comment by jaimiewashere** [comment]
hmm :thinking: can't think of anything...
can you check your pychromecast version?

**Comment by caleballen** [comment]
Yea, I'm running pychromecast6.0.0

**Comment by jaimiewashere** [comment]
Oh dear.. the latest [release](https://github.com/home-assistant-libs/pychromecast/releases) is pychromecast 10.1.1, I think..
What application reported that version? (are you using your package manager? does re-installing pychromecast with pip3 help?)
