### ISSUE TITLE
Crashes immediately when run

### ISSUE THREAD

**Issue by K4LCIFER** [muammar/mkchromecast#385]
It outputs the following when running `mkchromecast`

```
/usr/share/mkchromecast/mkchromecast/cast.py:111: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if iface is not None and iface[0]['addr'] is not '127.0.0.1':
Mkchromecast v0.3.8.1
Creating Pulseaudio Sink...
Open Pavucontrol and Select the Mkchromecast Sink.
Traceback (most recent call last):
  File "/usr/bin/mkchromecast", line 283, in <module>
    mk()
  File "/usr/bin/mkchromecast", line 53, in __init__
    self.audio_linux()
  File "/usr/bin/mkchromecast", line 68, in audio_linux
    create_sink()
  File "/usr/share/mkchromecast/mkchromecast/pulseaudio.py", line 35, in create_sink
    rs = subprocess.Popen(
  File "/usr/lib/python3.10/subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1842, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pacmd'
```

OS: Arch Linux
DE: Gnome Wayland
Installed with: AUR

**Comment by K4LCIFER** [comment]
The issue had to do with pipewire. Updated to master, and issue was solved.
