### ISSUE TITLE
Unable to cast video

### ISSUE THREAD

**Issue by K4LCIFER** [muammar/mkchromecast#386]
I'm not sure exactly wht is going on but perhaps this output is the culprit?

```
The media type string used is: video/mp4
PLAY command requested but no session is active.
```

**Comment by FingalP** [comment]
I get this too, can't find anything to help me debug why no session is active!

**Comment by TheGoesen** [comment]
Same here. Using raumfeld speakers, speakers are found, current status is displayed correctly but about everything I try fails with 
```
PLAY command requested but no session is active.
Traceback (most recent call last):
  File "/usr/bin/mkchromecast", line 288, in <module>
    CastProcess(mkcc).run()
  File "/usr/bin/mkchromecast", line 70, in run
    self.start_source_url()
  File "/usr/bin/mkchromecast", line 112, in start_source_url
    self.cc.play_cast()
  File "/usr/lib/python3.12/site-packages/mkchromecast/cast.py", line 339, in play_cast
    media_controller.play()
  File "/usr/lib/python3.12/site-packages/pychromecast/controllers/media.py", line 630, in play
    response_handler.wait_response()
  File "/usr/lib/python3.12/site-packages/pychromecast/response_handler.py", line 57, in wait_response
    raise RequestFailed(self._request)
pychromecast.error.RequestFailed: Failed to execute play.
```
