### ISSUE TITLE
I keep getting an error

### ISSUE THREAD

**Issue by htijs** [muammar/mkchromecast#388]
I get as far as the program recognizing my Chromecast on the Terminal or GUI but no connection. Terminal did give me this message: 

Note: I deleted the MAC ID for the Chromecast and IP Address since this is public.
[record[a,in-unique,(MAC ID Deleted for Security).local.]=120/119,(IP Address Deleted for Security):8009] Failed to connect, retrying in 5.0s

**Comment by MBfromOK** [comment]
I am also getting this error on Linux Mint 20.3 Cinnamon.

mkchromecast correctly detects the Chromecast but then fails to display anything (or play any audio)

I tried uninstalling and reinstalling, installing from the .deb file (matches the installed version)

FWIW: I made the mistake of running mkchromecast with 'sudo mkchromecast -t' in the attempt to see if it is a permissions error: 
```
Mkchromecast v0.3.8.1
Traceback (most recent call last):
  File "/usr/bin/mkchromecast", line 283, in <module>
    mk()
  File "/usr/bin/mkchromecast", line 37, in __init__
    mkchromecast.__init__.checkmktmp()
  File "/usr/share/mkchromecast/mkchromecast/__init__.py", line 875, in checkmktmp
    os.remove('/tmp/mkchromecast.tmp')
PermissionError: [Errno 1] Operation not permitted: '/tmp/mkchromecast.tmp'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_share_mkchromecast_mkchromecast.py.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/mkchromecast", line 283, in <module>
    mk()
  File "/usr/bin/mkchromecast", line 37, in __init__
    mkchromecast.__init__.checkmktmp()
  File "/usr/share/mkchromecast/mkchromecast/__init__.py", line 875, in checkmktmp
    os.remove('/tmp/mkchromecast.tmp')
PermissionError: [Errno 1] Operation not permitted: '/tmp/mkchromecast.tmp'
```
