### ISSUE TITLE
mkchromecast crash

### ISSUE THREAD

**Issue by J0nnyMak0** [muammar/mkchromecast#391]
I installed mkchromecast-git on on Arch Linux via aur. When I start mkchromecast, I get a crash:
```
Mkchromecast v0.3.9
Creating Pulseaudio Sink...
Open Pavucontrol and Select the Mkchromecast Sink.
Starting Local Streaming Server
[Done]
Selected backend: parec
Selected audio codec: mp3
Default bitrate used: 192k
Default sample rate used: 44100Hz.
No devices found!
 * Serving Flask app 'mkchromecast.audio' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
PID of main process: 1135
PID of streaming process: 1137
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "/usr/bin/mkchromecast", line 311, in <module>
    mk()
  File "/usr/bin/mkchromecast", line 59, in __init__
    self.audio_linux()
  File "/usr/bin/mkchromecast", line 78, in audio_linux
    self.cc.initialize_cast()
  File "/usr/lib/python3.10/site-packages/mkchromecast/cast.py", line 206, in initialize_cast
    remove_sink()
  File "/usr/lib/python3.10/site-packages/mkchromecast/pulseaudio.py", line 46, in remove_sink
    rms = subprocess.run(
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['pactl', 'unload-module', '']' returned non-zero exit status 1.
```

**Comment by Niklas20114552** [comment]
Same issue still here

**Comment by DigitalArtifex** [comment]
For others that have come across this issue:

This seems to be due to mkchromecast being dependent on pulseaudio and many have moved to pipewire. If you are using pulseaudio you simply need to install the package with pactl. For pulseaudio you will need to make some changes 

In `/usr/lib/python3/dist-packages/mkchromecast/pulseaudio.py` lines 16 and 42 need to be changed from `"pactl"` to `"ffmpeg"`. You will also need to install the respective ffmpeg package and codecs. After this you will need to use the screencast feature with `mkchromecast --video --screencast`. On my end there approx a 4 second delay, but I believe this is an ffmpeg issue as I have a similar issue with ffmpeg through Qt.

This was tested on Kubuntu 24.04
