### ISSUE TITLE
Using --video crashes the app

### ISSUE THREAD

**Issue by Darukutsu** [muammar/mkchromecast#445]
I just insalled `mkchromecast-git` package from aur and `--video` flag doesn't work.
I'm probably missing something... `python-soco` is installed

```
 $  mkchromecast --video --screencast --debug
ALSA device name: None
Google Cast name: None
backend: ffmpeg
USER =daru
PATH =/home/daru/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/home/daru/.local/share/cargo/bin:/home/daru/.config/rofi/scripts:/home/daru/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/android-ndk:/opt/android-sdk/tools:/opt/android-sdk/tools/bin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
ALSA device name: None
Google Cast name: None
backend: ffmpeg
Mkchromecast v0.3.9
Creating Pulseaudio Sink...
Open Pavucontrol and Select the Mkchromecast Sink.
Starting Video Cast Process...
ALSA device name: None
Google Cast name: None
backend: ffmpeg
ALSA device name: None
Google Cast name: None
backend: ffmpeg
:::ffmpeg::: pipeline_builder command: ['ffmpeg', '-ac', '2', '-ar', '44100', '-frame_size', '2048', '-fragment_size', '2048', '-f', 'pulse', '-ac', '2', '-i', 'Mkchromecast.monitor', '-f', 'x11grab', '-r', '25', '-s', '1920x1080', '-i', ':0+0,0', '-vcodec', 'libx264', '-preset', 'veryfast', '-tune', 'zerolatency', '-maxrate', '10000k', '-bufsize', '20000k', '-pix_fmt', 'yuv420p', '-g', '60', '-f', 'mp4', '-movflags', 'frag_keyframe+empty_moov', '-ar', '44100', '-acodec', 'libvorbis', 'pipe:1']
 * Serving Flask app 'mkchromecast'
 * Debug mode: off
PID of main process: 49163
PID of streaming process: 49235
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://192.168.0.135:5000
Press CTRL+C to quit
self.cclist [[0, 'Android TV', 'Gcast']]
if len(self.cclist) != 0 and self.mkcc.select_device == False:
 
List of Devices Available in Network:
-------------------------------------

Index   Types   Friendly Name 
=====   =====   ============= 
0 	Gcast 	Android TV
 
Casting to first device shown above!
Select devices by using the -s flag.
 
Android TV
 
def get_devices(self):
 
Information about  Android TV
 
def play_cast(self):
The IP of Android TV is: 192.168.0.101
Your local IP is: 192.168.0.135
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/mkchromecast/cast.py", line 346, in play_cast
    media_type = mkchromecast.video.mtype
                 ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'mkchromecast.video' has no attribute 'mtype'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/mkchromecast", line 335, in <module>
    CastProcess(mkcc).run()
  File "/usr/bin/mkchromecast", line 66, in run
    self.cast_video()
  File "/usr/bin/mkchromecast", line 153, in cast_video
    self.cc.play_cast()
  File "/usr/lib/python3.11/site-packages/mkchromecast/cast.py", line 387, in play_cast
    self.sonos.play_uri(
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'play_uri'
```

**Comment by xsdg** [comment]
Hi, thanks for reporting this.  This is a known issue.  I just filed a new bug to track moving away from having people use the mkchromecast `master` branch for everyday use.

**Comment by xsdg** [comment]
I should add — I've been away for the holidays, but I was already in the middle of a change that fixes this issue.  I should have it merged by the end of the week.
