### ISSUE TITLE
Unable to detect Sonos One speaker

### ISSUE THREAD

**Issue by michaelelleby** [muammar/mkchromecast#466]
I am using the code at Git commit `1d14cdfdc87bab288c889b073ac2e222e9a8309d`
```
> pip3 install soco
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: soco in /home/michael/.local/lib/python3.10/site-packages (0.30.4)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from soco) (2.25.1)
Requirement already satisfied: xmltodict in /home/michael/.local/lib/python3.10/site-packages (from soco) (0.13.0)
Requirement already satisfied: ifaddr in /usr/lib/python3/dist-packages (from soco) (0.1.7)
Requirement already satisfied: appdirs in /home/michael/.local/lib/python3.10/site-packages (from soco) (1.4.4)
Requirement already satisfied: lxml in /home/michael/.local/lib/python3.10/site-packages (from soco) (5.2.2)

> bin/mkchromecast -t
:::config::: WARNING: USING BETA CONFIG PATH: /home/michael/.config/mkchromecast/mkchromecast_beta.cfg
:::config::: Creating missing section 'settings'
:::config::: Missing keys _not_ being saved for read-only config
Mkchromecast v0.3.9
:::config::: WARNING: USING BETA CONFIG PATH: /home/michael/.config/mkchromecast/mkchromecast_beta.cfg
:::config::: Creating missing section 'settings'
:::config::: Missing keys _not_ being saved for read-only config
:::config::: WARNING: USING BETA CONFIG PATH: /home/michael/.config/mkchromecast/mkchromecast_beta.cfg
:::config::: Creating missing section 'settings'
:::config::: Missing keys _not_ being saved for read-only config
Selected backend: BackendInfo(name='parec', path='/usr/bin/parec')
Selected audio codec: mp3
Using bitrate: 192
Using sample rate: 44100Hz
:::config::: WARNING: USING BETA CONFIG PATH: /home/michael/.config/mkchromecast/mkchromecast_beta.cfg
:::config::: Creating missing section 'settings'
:::config::: Missing keys _not_ being saved for read-only config
:::config::: WARNING: USING BETA CONFIG PATH: /home/michael/.config/mkchromecast/mkchromecast_beta.cfg
:::config::: Creating missing section 'settings'
:::config::: Missing keys _not_ being saved for read-only config
:::config::: WARNING: USING BETA CONFIG PATH: /home/michael/.config/mkchromecast/mkchromecast_beta.cfg
:::config::: Creating missing section 'settings'
:::config::: Missing keys _not_ being saved for read-only config
 
List of Devices Available in Network:
-------------------------------------

Index   Type    Friendly Name 
=====   =====   ============= 
0 	Gcast 	Soveværelse
1 	Gcast 	Legestue Google TV
2 	Gcast 	Stue TV
available_devices received
Available Media Streaming Devices [AvailableDevice(index=0, name='Soveværelse', type='Gcast'), AvailableDevice(index=1, name='Legestue Google TV', type='Gcast'), AvailableDevice(index=2, name='Stue TV', type='Gcast')]
```

I have a Sonos One speaker running at 192.168.1.122 and it is reachable using https://github.com/pascalopitz/unoffical-sonos-controller-for-linux which is to say that I can reach it from my Linux pc. As seen in the log above mkchromecast does not detect it.

**Comment by xsdg** [comment]
I just filed #467 to track restoring Sonos support.

**Comment by michaelelleby** [comment]
Unfortunately neither `stable` branch nor commit `07598801` worked
```
~/git/mkchromecast$ git status
HEAD detached at 07598801
nothing to commit, working tree clean

~/git/mkchromecast$ ./bin/mkchromecast -t
:::config::: WARNING: USING BETA CONFIG PATH: /home/michael/.config/mkchromecast/mkchromecast_beta.cfg
:::config::: Creating missing section 'settings'
:::config::: Missing keys _not_ being saved for read-only config
Mkchromecast v0.3.9
:::config::: WARNING: USING BETA CONFIG PATH: /home/michael/.config/mkchromecast/mkchromecast_beta.cfg
:::config::: Creating missing section 'settings'
:::config::: Missing keys _not_ being saved for read-only config
:::config::: WARNING: USING BETA CONFIG PATH: /home/michael/.config/mkchromecast/mkchromecast_beta.cfg
:::config::: Creating missing section 'settings'
:::config::: Missing keys _not_ being saved for read-only config
Selected backend: BackendInfo(name='parec', path='/usr/bin/parec')
Selected audio codec: mp3
Using bitrate: 192
Using sample rate: 44100Hz
:::config::: WARNING: USING BETA CONFIG PATH: /home/michael/.config/mkchromecast/mkchromecast_beta.cfg
:::config::: Creating missing section 'settings'
:::config::: Missing keys _not_ being saved for read-only config
:::config::: WARNING: USING BETA CONFIG PATH: /home/michael/.config/mkchromecast/mkchromecast_beta.cfg
:::config::: Creating missing section 'settings'
:::config::: Missing keys _not_ being saved for read-only config
:::config::: WARNING: USING BETA CONFIG PATH: /home/michael/.config/mkchromecast/mkchromecast_beta.cfg
:::config::: Creating missing section 'settings'
:::config::: Missing keys _not_ being saved for read-only config
 
List of Devices Available in Network:
-------------------------------------

Index   Types   Friendly Name 
=====   =====   ============= 
0 	Gcast 	Legestue Google TV
1 	Gcast 	Soveværelse
2 	Gcast 	Stue TV
available_devices received
Available Media Streaming Devices [[0, 'Legestue Google TV', 'Gcast'], [1, 'Soveværelse', 'Gcast'], [2, 'Stue TV', 'Gcast']]

~/git/mkchromecast$ git checkout stable
Previous HEAD position was 07598801 Merge pull request #456 from xsdg/noop_fixups
Switched to branch 'stable'
Your branch is up to date with 'origin/stable'.

~/git/mkchromecast$ ./bin/mkchromecast -t
Mkchromecast v0.3.9
Selected backend: /usr/bin/parec
Selected audio codec: mp3
Default bitrate used: 192k
Default sample rate used: 44100Hz.
 
List of Devices Available in Network:
-------------------------------------

Index   Types   Friendly Name 
=====   =====   ============= 
0 	Gcast 	Legestue Google TV
1 	Gcast 	Soveværelse
2 	Gcast 	Stue TV
available_devices received
Available Media Streaming Devices [[0, 'Legestue Google TV', 'Gcast'], [1, 'Soveværelse', 'Gcast'], [2, 'Stue TV', 'Gcast']]
```

**Comment by xsdg** [comment]
Could you try `mkchromecast --debug --discover`?  That will enable debug output while showing which devices are available.

**Comment by muammar** [comment]
> mkchromecast --debug --discover

This does not work either: 

```
muammar@pupa ~/git/mkchromecast [master]
± % bin/mkchromecast --debug --discover                                                                                                                                                                         !3222
Traceback (most recent call last):
  File "/Users/muammar/git/mkchromecast/bin/mkchromecast", line 285, in <module>
    mkcc = mkchromecast.Mkchromecast()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/muammar/git/mkchromecast/bin/../mkchromecast/__init__.py", line 194, in __init__
    elif self.codec in constants.CODECS_WITH_BITRATE:
         ^^^^^^^^^^
AttributeError: 'Mkchromecast' object has no attribute 'codec'. Did you mean: 'vcodec'?
```
