### ISSUE TITLE
`self.codec` is not set appropriately on Mac

### ISSUE THREAD

**Issue by xsdg** [muammar/mkchromecast#468]
Found by @muammar in #466 

```
muammar@pupa ~/git/mkchromecast [master]
± % bin/mkchromecast --debug --discover                                                                                                                                                                         !3222
Traceback (most recent call last):
  File "/Users/muammar/git/mkchromecast/bin/mkchromecast", line 285, in <module>
    mkcc = mkchromecast.Mkchromecast()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/muammar/git/mkchromecast/bin/../mkchromecast/__init__.py", line 194, in __init__
    elif self.codec in constants.CODECS_WITH_BITRATE:
         ^^^^^^^^^^
AttributeError: 'Mkchromecast' object has no attribute 'codec'. Did you mean: 'vcodec'?
```

The issue is here: \
https://github.com/muammar/mkchromecast/blob/1d14cdfdc87bab288c889b073ac2e222e9a8309d/mkchromecast/__init__.py#L144

On Mac, the default backend is `"node"` and the default codec is `"mp3"`, which is the only codec supported by the node backend.  When `args.codec` is set to anything else, we override and set `self.codec` to `"mp3"`, which is correct.  But when `args.codec` is correct, we never copy it into `self.codec`, and `self.codec` remains unset.

**Comment by xsdg** [comment]
@psmgeelen Is this something you'd like to work on?  No worries if not.  If so, let me know how much guidance would be helpful.

**Comment by psmgeelen** [comment]
@xsdg Yes! I would be. In terms of support, I would like to point out that I don't own a Mac, even though by the look of this, it doesn't seem that I really need one. Let me review properly this weekend and get back to you with a PR. What was the formatting again so I can connect my PR to the issue?

**Comment by xsdg** [comment]
Sounds good.  I would suggest writing a new unit test that replicates this issue (see https://github.com/muammar/mkchromecast/blob/master/tests/test_instantiate.py ), and then making sure that your fix causes that unit test to start passing.

As for connecting things, you can mention an issue with `#<issue number>`.  As for the actual integrations, see https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Comment by psmgeelen** [comment]
@xsdg I hope this is what you needed :)

**Comment by xsdg** [comment]
@muammar Could you confirm whether this bug is fixed?

**Comment by psmgeelen** [comment]
@xsdg Let me know if you have something else for me to fix ;)

**Comment by muammar** [comment]
> @muammar Could you confirm whether this bug is fixed?

It's fixed.  I wanted to find the problem with the Sonos list not being populated, but got caught up with some stuff at work. Thanks for the follow up.
