### ISSUE TITLE
OSX system tray unable to launch

### ISSUE THREAD

**Issue by kennykaye** [muammar/mkchromecast#5]
**TL;DR**

Unable to launch mkchromecast on OSX from either homebrew version or prebuild dmg.

**Observed Behavior**:

When installing mkhromecast via `brew cask install mkchromecast` then launching the application, a UI message appears with the following message:

<img width="621" alt="screen shot 2016-07-02 at 7 50 23 pm" src="https://cloud.githubusercontent.com/assets/3267574/16543553/48851f16-408e-11e6-8284-4a22cf63e20f.png">

Upon inspection of the logs the following errors are reported:

```log
7/2/16 7:22:45.000 PM	kernel[0]	hfs: mounted mkchromecast on device disk2s1
7/2/16 7:22:48.000 PM	kernel[0]	hfs: unmount initiated on mkchromecast on device disk2s1
7/2/16 7:22:58.113 PM	mkchromecast[3434]	[0m[04mSelected backend:[0m node
7/2/16 7:22:58.113 PM	mkchromecast[3434]	[0m[04mSelected audio codec:[0m mp3
7/2/16 7:22:58.181 PM	mkchromecast[3434]	mkchromecast Error
7/2/16 7:22:58.181 PM	mkchromecast[3434]	2016-07-02 19:22:58.181 mkchromecast[3434:23970] mkchromecast Error
7/2/16 7:23:00.407 PM	mkchromecast[3434]	Traceback (most recent call last):
7/2/16 7:23:00.407 PM	mkchromecast[3434]	  File "/Applications/mkchromecast.app/Contents/Resources/__boot__.py", line 351, in <module>
7/2/16 7:23:00.407 PM	mkchromecast[3434]	    _run()
7/2/16 7:23:00.407 PM	mkchromecast[3434]	  File "/Applications/mkchromecast.app/Contents/Resources/__boot__.py", line 336, in _run
7/2/16 7:23:00.407 PM	mkchromecast[3434]	    exec(compile(source, path, 'exec'), globals(), globals())
7/2/16 7:23:00.407 PM	mkchromecast[3434]	  File "/Applications/mkchromecast.app/Contents/Resources/start_tray.py", line 14, in <module>
7/2/16 7:23:00.407 PM	mkchromecast[3434]	    mkchromecast.systray.main()
7/2/16 7:23:00.407 PM	mkchromecast[3434]	  File "mkchromecast/systray.pyc", line 623, in main
7/2/16 7:23:00.407 PM	mkchromecast[3434]	  File "mkchromecast/systray.pyc", line 38, in __init__
7/2/16 7:23:00.407 PM	mkchromecast[3434]	  File "mkchromecast/cast.pyc", line 41, in __init__
7/2/16 7:23:00.407 PM	mkchromecast[3434]	socket.gaierror: [Errno 8] nodename nor servname provided, or not known
7/2/16 7:23:18.062 PM	mkchromecast[3451]	[0m[04mSelected backend:[0m node
7/2/16 7:23:18.062 PM	mkchromecast[3451]	[0m[04mSelected audio codec:[0m mp3
7/2/16 7:23:18.132 PM	mkchromecast[3451]	mkchromecast Error
7/2/16 7:23:18.133 PM	mkchromecast[3451]	2016-07-02 19:23:18.132 mkchromecast[3451:24270] mkchromecast Error
7/2/16 7:23:19.841 PM	mkchromecast[3451]	Traceback (most recent call last):
7/2/16 7:23:19.842 PM	mkchromecast[3451]	  File "/Applications/mkchromecast.app/Contents/Resources/__boot__.py", line 351, in <module>
7/2/16 7:23:19.842 PM	mkchromecast[3451]	    _run()
7/2/16 7:23:19.842 PM	mkchromecast[3451]	  File "/Applications/mkchromecast.app/Contents/Resources/__boot__.py", line 336, in _run
7/2/16 7:23:19.842 PM	mkchromecast[3451]	    exec(compile(source, path, 'exec'), globals(), globals())
7/2/16 7:23:19.842 PM	mkchromecast[3451]	  File "/Applications/mkchromecast.app/Contents/Resources/start_tray.py", line 14, in <module>
7/2/16 7:23:19.842 PM	mkchromecast[3451]	    mkchromecast.systray.main()
7/2/16 7:23:19.842 PM	mkchromecast[3451]	  File "mkchromecast/systray.pyc", line 623, in main
7/2/16 7:23:19.842 PM	mkchromecast[3451]	  File "mkchromecast/systray.pyc", line 38, in __init__
7/2/16 7:23:19.842 PM	mkchromecast[3451]	  File "mkchromecast/cast.pyc", line 41, in __init__
7/2/16 7:23:19.842 PM	mkchromecast[3451]	socket.gaierror: [Errno 8] nodename nor servname provided, or not known
7/2/16 7:24:39.000 PM	kernel[0]	hfs: mounted mkchromecast on device disk2s1
7/2/16 7:24:39.111 PM	mds[68]	(Volume.Normal:2464) volume:0x7f99c789fe00 ********** Bootstrapped Creating a default store:1 SpotLoc:(null) SpotVerLoc:(null) occlude:0 /Volumes/mkchromecast
7/2/16 7:25:03.777 PM	com.apple.xpc.launchd[1]	(com.apple.xpc.launchd.oneshot.0x10000009.mkchromecast[3637]) Service exited due to signal: Killed: 9
7/2/16 7:25:21.937 PM	com.apple.xpc.launchd[1]	(com.apple.xpc.launchd.oneshot.0x1000000a.mkchromecast[3652]) Service exited due to signal: Killed: 9
7/2/16 7:25:40.800 PM	launchservicesd[86]	Someone attempted to start application App:"mkchromecast" asn:0x0-77077 pid:3667 refs=6 @ 0x7f8e2a470090 but it still has _kLSApplicationLockedInStoppedStateKey=true, so it is is staying stopped. : LASApplication.cp #2661 SetApplicationInStoppedState() q=LSSession 100007/0x186a7 queue
7/2/16 7:25:44.000 PM	com.apple.xpc.launchd[1]	(com.apple.xpc.launchd.oneshot.0x1000000b.mkchromecast[3667]) Service exited due to signal: Killed: 9
7/2/16 7:25:53.829 PM	CoreServicesUIAgent[344]	error -1 while removing quarantine data on path /Applications/mkchromecast.app/Contents/Frameworks/Python.framework/Python
7/2/16 7:25:53.829 PM	CoreServicesUIAgent[344]	error -1 while removing quarantine data on path /Applications/mkchromecast.app/Contents/Frameworks/Python.framework/Resources
7/2/16 7:25:53.830 PM	CoreServicesUIAgent[344]	error -1 while removing quarantine data on path /Applications/mkchromecast.app/Contents/Frameworks/Python.framework/Versions/Current
7/2/16 7:25:53.831 PM	CoreServicesUIAgent[344]	error -1 while removing quarantine data on path /Applications/mkchromecast.app/Contents/Frameworks/Qt3DCore.framework/Qt3DCore
7/2/16 7:25:53.831 PM	CoreServicesUIAgent[344]	error -1 while removing quarantine data on path /Applications/mkchromecast.app/Contents/Frameworks/Qt3DCore.framework/Resources
7/2/16 7:25:53.831 PM	CoreServicesUIAgent[344]	error -1 while removing quarantine data on path /Applications/mkchromecast.app/Contents/Frameworks/Qt3DCore.framework/Versions/Current
7/2/16 7:25:53.832 PM	CoreServicesUIAgent[344]	error -1 while removing quarantine data on path /Applications/mkchromecast.app/Contents/Frameworks/Qt3DRender.framework/Qt3DRender
7/2/16 7:25:53.832 PM	CoreServicesUIAgent[344]	error -1 while removing quarantine data on path /Applications/mkchromecast.app/Contents/Frameworks/Qt3DRender.framework/Resources
7/2/16 7:25:53.832 PM	CoreServicesUIAgent[344]	error -1 while removing quarantine data on path /Applications/mkchromecast.app/Contents/Frameworks/Qt3DRender.framework/Versions/Current
7/2/16 7:25:53.832 PM	CoreServicesUIAgent[344]	error -1 while removing quarantine data on path /Applications/mkchromecast.app/Contents/Frameworks/QtConcurrent.framework/QtConcurrent
7/2/16 7:25:53.833 PM	CoreServicesUIAgent[344]	error -1 while removing quarantine data on path /Applications/mkchromecast.app/Contents/Frameworks/QtConcurrent.framework/Resources
7/2/16 7:25:53.833 PM	CoreServicesUIAgent[344]	error -1 while removing quarantine data on path /Applications/mkchromecast.app/Contents/Frameworks/QtConcurrent.framework/Versions/Current
7/2/16 7:25:53.833 PM	CoreServicesUIAgent[344]	error -1 while removing quarantine data on path /Applications/mkchromecast.app/Contents/Frameworks/QtCore.framework/QtCore
7/2/16 7:25:53.834 PM	CoreServicesUIAgent[344]	error -1 while removing quarantine data on path /Applications/mkchromecast.app/Contents/Frameworks/QtCore.framework/Resources
7/2/16 7:25:53.834 PM	CoreServicesUIAgent[344]	error -1 while removing quarantine data on path /Applications/mkchromecast.app/Contents/Frameworks/QtCore.framework/Versions/Current
7/2/16 7:25:53.834 PM	CoreServicesUIAgent[344]	error -1 while removing quarantine data on path /Applications/mkchromecast.app/Contents/Frameworks/QtDesigner.framework/QtDesigner
7/2/16 7:25:53.834 PM	CoreServicesUIAgent[344]	error -1 while removing quarantine data on path /Applications/mkchromecast.app/Contents/Frameworks/QtDesigner.framework/Resources
7/2/16 7:25:53.835 PM	CoreServicesUIAgent[344]	error -1 while removing quarantine data on path /Applications/mkchromecast.app/Contents/Frameworks/QtDesigner.framework/Versions/Current
7/2/16 7:25:53.835 PM	CoreServicesUIAgent[344]	error -1 while removing quarantine data on path /Applications/mkchromecast.app/Contents/Frameworks/QtGui.framework/QtGui
7/2/16 7:25:53.835 PM	CoreServicesUIAgent[344]	error -1 while removing quarantine data on path /Applications/mkchromecast.app/Contents/Frameworks/QtGui.framework/Resources
7/2/16 7:25:53.835 PM	CoreServicesUIAgent[344]	error -1 while removing quarantine data on path /Applications/mkchromecast.app/Contents/Frameworks/QtGui.framework/Versions/Current
7/2/16 7:25:53.836 PM	CoreServicesUIAgent[344]	error -1 while removing quarantine data on path /Applications/mkchromecast.app/Contents/Frameworks/QtLocation.framework/QtLocation
7/2/16 7:25:53.836 PM	CoreServicesUIAgent[344]	error -1 while removing quarantine data on path /Applications/mkchromecast.app/Contents/Frameworks/QtLocation.framework/Resources
7/2/16 7:25:53.836 PM	CoreServicesUIAgent[344]	error -1 while removing quarantine data on path /Applications/mkchromecast.app/Contents/Frameworks/QtLocation.framework/Versions/Current
7/2/16 7:25:53.836 PM	CoreServicesUIAgent[344]	error -1 while removing quarantine data on path /Applications/mkchromecast.app/Contents/Frameworks/QtMultimedia.framework/QtMultimedia
7/2/16 7:25:53.836 PM	CoreServicesUIAgent[344]	error -1 while removing quarantine data on path /Applications/mkchromecast.app/Contents/Frameworks/QtMultimedia.framework/Resources
7/2/16 7:25:53.837 PM	CoreServicesUIAgent[344]	error -1 while removing quarantine data on path /Applications/mkchromecast.app/Contents/Frameworks/QtMultimedia.framework/Versions/Current
7/2/16 7:25:53.837 PM	CoreServicesUIAgent[344]	error -1 while removing quarantine data on path /Applications/mkchromecast.app/Contents/Frameworks/QtMultimediaWidgets.framework/QtMultimediaWidgets
7/2/16 7:25:53.837 PM	CoreServicesUIAgent[344]	error -1 while removing quarantine data on path /Applications/mkchromecast.app/Contents/Frameworks/QtMultimediaWidgets.framework/Resources
7/2/16 7:25:53.838 PM	CoreServicesUIAgent[344]	error -1 while removing quarantine data on path /Applications/mkchromecast.app/Contents/Frameworks/QtMultimediaWidgets.framework/Versions/Current
7/2/16 7:25:53.838 PM	CoreServicesUIAgent[344]	error -1 while removing quarantine data on path /Applications/mkchromecast.app/Contents/Frameworks/QtNetwork.framework/QtNetwork
7/2/16 7:25:53.838 PM	CoreServicesUIAgent[344]	error -1 while removing quarantine data on path /Applications/mkchromecast.app/Contents/Frameworks/QtNetwork.framework/Resources
7/2/16 7:25:53.838 PM	CoreServicesUIAgent[344]	error -1 while removing quarantine data on path /Applications/mkchromecast.app/Contents/Frameworks/QtNetwork.framework/Versions/Current
7/2/16 7:25:53.839 PM	CoreServicesUIAgent[344]	error -1 while removing quarantine data on path /Applications/mkchromecast.app/Contents/Frameworks/QtOpenGL.framework/QtOpenGL
7/2/16 7:25:53.839 PM	CoreServicesUIAgent[344]	error -1 while removing quarantine data on path /Applications/mkchromecast.app/Contents/Frameworks/QtOpenGL.framework/Resources
7/2/16 7:25:53.839 PM	CoreServicesUIAgent[344]	error -1 while removing quarantine data on path /Applications/mkchromecast.app/Contents/Frameworks/QtOpenGL.framework/Versions/Current
7/2/16 7:25:53.839 PM	CoreServicesUIAgent[344]	error -1 while removing quarantine data on path /Applications/mkchromecast.app/Contents/Frameworks/QtPositioning.framework/QtPositioning
7/2/16 7:25:53.839 PM	CoreServicesUIAgent[344]	error -1 while removing quarantine data on path /Applications/mkchromecast.app/Contents/Frameworks/QtPositioning.framework/Resources
7/2/16 7:25:53.840 PM	CoreServicesUIAgent[344]	error -1 while removing quarantine data on path /Applications/mkchromecast.app/Contents/Frameworks/QtPositioning.framework/Versions/Current
7/2/16 7:25:53.840 PM	CoreServicesUIAgent[344]	error -1 while removing quarantine data on path /Applications/mkchromecast.app/Contents/Frameworks/QtPrintSupport.framework/QtPrintSupport
7/2/16 7:25:53.840 PM	CoreServicesUIAgent[344]	error -1 while removing quarantine data on path /Applications/mkchromecast.app/Contents/Frameworks/QtPrintSupport.framework/Resources
7/2/16 7:25:53.840 PM	CoreServicesUIAgent[344]	error -1 while removing quarantine data on path /Applications/mkchromecast.app/Contents/Frameworks/QtPrintSupport.framework/Versions/Current
7/2/16 7:25:53.840 PM	CoreServicesUIAgent[344]	error -1 while removing quarantine data on path /Applications/mkchromecast.app/Contents/Frameworks/QtQml.framework/QtQml
7/2/16 7:25:53.841 PM	CoreServicesUIAgent[344]	error -1 while removing quarantine data on path /Applications/mkchromecast.app/Contents/Frameworks/QtQml.framework/Resources
7/2/16 7:25:53.841 PM	CoreServicesUIAgent[344]	error -1 while removing quarantine data on path /Applications/mkchromecast.app/Contents/Frameworks/QtQml.framework/Versions/Current
7/2/16 7:25:53.841 PM	CoreServicesUIAgent[344]	error -1 while removing quarantine data on path /Applications/mkchromecast.app/Contents/Frameworks/QtQuick.framework/QtQuick
7/2/16 7:25:53.841 PM	CoreServicesUIAgent[344]	error -1 while removing quarantine data on path /Applications/mkchromecast.app/Contents/Frameworks/QtQuick.framework/Resources
7/2/16 7:25:53.842 PM	CoreServicesUIAgent[344]	error -1 while removing quarantine data on path /Applications/mkchromecast.app/Contents/Frameworks/QtQuick.framework/Versions/Current
7/2/16 7:25:53.842 PM	CoreServicesUIAgent[344]	error -1 while removing quarantine data on path /Applications/mkchromecast.app/Contents/Frameworks/QtQuickWidgets.framework/QtQuickWidgets
7/2/16 7:25:53.842 PM	CoreServicesUIAgent[344]	error -1 while removing quarantine data on path /Applications/mkchromecast.app/Contents/Frameworks/QtQuickWidgets.framework/Resources
7/2/16 7:25:53.842 PM	CoreServicesUIAgent[344]	error -1 while removing quarantine data on path /Applications/mkchromecast.app/Contents/Frameworks/QtQuickWidgets.framework/Versions/Current
7/2/16 7:25:53.842 PM	CoreServicesUIAgent[344]	error -1 while removing quarantine data on path /Applications/mkchromecast.app/Contents/Frameworks/QtSensors.framework/QtSensors
7/2/16 7:25:53.843 PM	CoreServicesUIAgent[344]	error -1 while removing quarantine data on path /Applications/mkchromecast.app/Contents/Frameworks/QtSensors.framework/Resources
7/2/16 7:25:53.843 PM	CoreServicesUIAgent[344]	error -1 while removing quarantine data on path /Applications/mkchromecast.app/Contents/Frameworks/QtSensors.framework/Versions/Current
7/2/16 7:25:53.843 PM	CoreServicesUIAgent[344]	error -1 while removing quarantine data on path /Applications/mkchromecast.app/Contents/Frameworks/QtSerialBus.framework/QtSerialBus
7/2/16 7:25:53.843 PM	CoreServicesUIAgent[344]	error -1 while removing quarantine data on path /Applications/mkchromecast.app/Contents/Frameworks/QtSerialBus.framework/Resources
7/2/16 7:25:53.843 PM	CoreServicesUIAgent[344]	error -1 while removing quarantine data on path /Applications/mkchromecast.app/Contents/Frameworks/QtSerialBus.framework/Versions/Current
7/2/16 7:25:53.844 PM	CoreServicesUIAgent[344]	error -1 while removing quarantine data on path /Applications/mkchromecast.app/Contents/Frameworks/QtSerialPort.framework/QtSerialPort
7/2/16 7:25:53.844 PM	CoreServicesUIAgent[344]	error -1 while removing quarantine data on path /Applications/mkchromecast.app/Contents/Frameworks/QtSerialPort.framework/Resources
7/2/16 7:25:53.844 PM	CoreServicesUIAgent[344]	error -1 while removing quarantine data on path /Applications/mkchromecast.app/Contents/Frameworks/QtSerialPort.framework/Versions/Current
7/2/16 7:25:53.844 PM	CoreServicesUIAgent[344]	error -1 while removing quarantine data on path /Applications/mkchromecast.app/Contents/Frameworks/QtSql.framework/QtSql
7/2/16 7:25:53.844 PM	CoreServicesUIAgent[344]	error -1 while removing quarantine data on path /Applications/mkchromecast.app/Contents/Frameworks/QtSql.framework/Resources
7/2/16 7:25:53.845 PM	CoreServicesUIAgent[344]	error -1 while removing quarantine data on path /Applications/mkchromecast.app/Contents/Frameworks/QtSql.framework/Versions/Current
7/2/16 7:25:53.845 PM	CoreServicesUIAgent[344]	error -1 while removing quarantine data on path /Applications/mkchromecast.app/Contents/Frameworks/QtSvg.framework/QtSvg
7/2/16 7:25:53.845 PM	CoreServicesUIAgent[344]	error -1 while removing quarantine data on path /Applications/mkchromecast.app/Contents/Frameworks/QtSvg.framework/Resources
7/2/16 7:25:53.845 PM	CoreServicesUIAgent[344]	error -1 while removing quarantine data on path /Applications/mkchromecast.app/Contents/Frameworks/QtSvg.framework/Versions/Current
7/2/16 7:25:53.845 PM	CoreServicesUIAgent[344]	error -1 while removing quarantine data on path /Applications/mkchromecast.app/Contents/Frameworks/QtWidgets.framework/QtWidgets
7/2/16 7:25:53.846 PM	CoreServicesUIAgent[344]	error -1 while removing quarantine data on path /Applications/mkchromecast.app/Contents/Frameworks/QtWidgets.framework/Resources
7/2/16 7:25:53.846 PM	CoreServicesUIAgent[344]	error -1 while removing quarantine data on path /Applications/mkchromecast.app/Contents/Frameworks/QtWidgets.framework/Versions/Current
7/2/16 7:25:53.846 PM	CoreServicesUIAgent[344]	error -1 while removing quarantine data on path /Applications/mkchromecast.app/Contents/Frameworks/QtXml.framework/QtXml
7/2/16 7:25:53.846 PM	CoreServicesUIAgent[344]	error -1 while removing quarantine data on path /Applications/mkchromecast.app/Contents/Frameworks/QtXml.framework/Resources
7/2/16 7:25:53.847 PM	CoreServicesUIAgent[344]	error -1 while removing quarantine data on path /Applications/mkchromecast.app/Contents/Frameworks/QtXml.framework/Versions/Current
7/2/16 7:25:53.864 PM	CoreServicesUIAgent[344]	error -1 while removing quarantine data on path /Applications/mkchromecast.app/Contents/Resources/lib/python3.5/site.pyc
7/2/16 7:25:56.933 PM	mkchromecast[3675]	[0m[04mSelected backend:[0m node
7/2/16 7:25:56.934 PM	mkchromecast[3675]	[0m[04mSelected audio codec:[0m mp3
7/2/16 7:25:57.005 PM	mkchromecast[3675]	mkchromecast Error
7/2/16 7:25:57.006 PM	mkchromecast[3675]	2016-07-02 19:25:57.005 mkchromecast[3675:27404] mkchromecast Error
7/2/16 7:25:58.981 PM	mkchromecast[3675]	Traceback (most recent call last):
7/2/16 7:25:58.982 PM	mkchromecast[3675]	  File "/Applications/mkchromecast.app/Contents/Resources/__boot__.py", line 351, in <module>
7/2/16 7:25:58.982 PM	mkchromecast[3675]	    _run()
7/2/16 7:25:58.982 PM	mkchromecast[3675]	  File "/Applications/mkchromecast.app/Contents/Resources/__boot__.py", line 336, in _run
7/2/16 7:25:58.982 PM	mkchromecast[3675]	    exec(compile(source, path, 'exec'), globals(), globals())
7/2/16 7:25:58.982 PM	mkchromecast[3675]	  File "/Applications/mkchromecast.app/Contents/Resources/start_tray.py", line 14, in <module>
7/2/16 7:25:58.982 PM	mkchromecast[3675]	    mkchromecast.systray.main()
7/2/16 7:25:58.982 PM	mkchromecast[3675]	  File "mkchromecast/systray.pyc", line 623, in main
7/2/16 7:25:58.982 PM	mkchromecast[3675]	  File "mkchromecast/systray.pyc", line 38, in __init__
7/2/16 7:25:58.982 PM	mkchromecast[3675]	  File "mkchromecast/cast.pyc", line 41, in __init__
7/2/16 7:25:58.982 PM	mkchromecast[3675]	socket.gaierror: [Errno 8] nodename nor servname provided, or not known
7/2/16 7:34:11.915 PM	mkchromecast[17569]	[0m[04mSelected backend:[0m node
7/2/16 7:34:11.915 PM	mkchromecast[17569]	[0m[04mSelected audio codec:[0m mp3
7/2/16 7:34:11.983 PM	mkchromecast[17569]	mkchromecast Error
7/2/16 7:34:11.983 PM	mkchromecast[17569]	2016-07-02 19:34:11.983 mkchromecast[17569:63478] mkchromecast Error
7/2/16 7:34:14.350 PM	mkchromecast[17569]	Traceback (most recent call last):
7/2/16 7:34:14.351 PM	mkchromecast[17569]	  File "/Applications/mkchromecast.app/Contents/Resources/__boot__.py", line 351, in <module>
7/2/16 7:34:14.351 PM	mkchromecast[17569]	    _run()
7/2/16 7:34:14.351 PM	mkchromecast[17569]	  File "/Applications/mkchromecast.app/Contents/Resources/__boot__.py", line 336, in _run
7/2/16 7:34:14.351 PM	mkchromecast[17569]	    exec(compile(source, path, 'exec'), globals(), globals())
7/2/16 7:34:14.351 PM	mkchromecast[17569]	  File "/Applications/mkchromecast.app/Contents/Resources/start_tray.py", line 14, in <module>
7/2/16 7:34:14.351 PM	mkchromecast[17569]	    mkchromecast.systray.main()
7/2/16 7:34:14.351 PM	mkchromecast[17569]	  File "mkchromecast/systray.pyc", line 623, in main
7/2/16 7:34:14.351 PM	mkchromecast[17569]	  File "mkchromecast/systray.pyc", line 38, in __init__
7/2/16 7:34:14.351 PM	mkchromecast[17569]	  File "mkchromecast/cast.pyc", line 41, in __init__
7/2/16 7:34:14.351 PM	mkchromecast[17569]	socket.gaierror: [Errno 8] nodename nor servname provided, or not known
7/2/16 7:43:05.702 PM	mkchromecast[31598]	[0m[04mSelected backend:[0m node
7/2/16 7:43:05.702 PM	mkchromecast[31598]	[0m[04mSelected audio codec:[0m mp3
7/2/16 7:43:05.771 PM	mkchromecast[31598]	mkchromecast Error
7/2/16 7:43:05.771 PM	mkchromecast[31598]	2016-07-02 19:43:05.770 mkchromecast[31598:83458] mkchromecast Error
7/2/16 7:43:07.359 PM	mkchromecast[31598]	Traceback (most recent call last):
7/2/16 7:43:07.359 PM	mkchromecast[31598]	  File "/Applications/mkchromecast.app/Contents/Resources/__boot__.py", line 351, in <module>
7/2/16 7:43:07.359 PM	mkchromecast[31598]	    _run()
7/2/16 7:43:07.359 PM	mkchromecast[31598]	  File "/Applications/mkchromecast.app/Contents/Resources/__boot__.py", line 336, in _run
7/2/16 7:43:07.359 PM	mkchromecast[31598]	    exec(compile(source, path, 'exec'), globals(), globals())
7/2/16 7:43:07.360 PM	mkchromecast[31598]	  File "/Applications/mkchromecast.app/Contents/Resources/start_tray.py", line 14, in <module>
7/2/16 7:43:07.360 PM	mkchromecast[31598]	    mkchromecast.systray.main()
7/2/16 7:43:07.360 PM	mkchromecast[31598]	  File "mkchromecast/systray.pyc", line 623, in main
7/2/16 7:43:07.360 PM	mkchromecast[31598]	  File "mkchromecast/systray.pyc", line 38, in __init__
7/2/16 7:43:07.360 PM	mkchromecast[31598]	  File "mkchromecast/cast.pyc", line 41, in __init__
7/2/16 7:43:07.360 PM	mkchromecast[31598]	socket.gaierror: [Errno 8] nodename nor servname provided, or not known
7/2/16 7:44:24.000 PM	kernel[0]	hfs: mounted mkchromecast on device disk3s1
7/2/16 7:44:28.000 PM	kernel[0]	hfs: unmount initiated on mkchromecast on device disk3s1
7/2/16 7:44:53.362 PM	mkchromecast[31840]	[0m[04mSelected backend:[0m node
7/2/16 7:44:53.362 PM	mkchromecast[31840]	[0m[04mSelected audio codec:[0m mp3
7/2/16 7:44:53.431 PM	mkchromecast[31840]	mkchromecast Error
7/2/16 7:44:53.431 PM	mkchromecast[31840]	2016-07-02 19:44:53.430 mkchromecast[31840:85259] mkchromecast Error
7/2/16 7:44:55.130 PM	mkchromecast[31840]	Traceback (most recent call last):
7/2/16 7:44:55.130 PM	mkchromecast[31840]	  File "/Applications/mkchromecast.app/Contents/Resources/__boot__.py", line 351, in <module>
7/2/16 7:44:55.130 PM	mkchromecast[31840]	    _run()
7/2/16 7:44:55.130 PM	mkchromecast[31840]	  File "/Applications/mkchromecast.app/Contents/Resources/__boot__.py", line 336, in _run
7/2/16 7:44:55.130 PM	mkchromecast[31840]	    exec(compile(source, path, 'exec'), globals(), globals())
7/2/16 7:44:55.130 PM	mkchromecast[31840]	  File "/Applications/mkchromecast.app/Contents/Resources/start_tray.py", line 14, in <module>
7/2/16 7:44:55.130 PM	mkchromecast[31840]	    mkchromecast.systray.main()
7/2/16 7:44:55.130 PM	mkchromecast[31840]	  File "mkchromecast/systray.pyc", line 623, in main
7/2/16 7:44:55.130 PM	mkchromecast[31840]	  File "mkchromecast/systray.pyc", line 38, in __init__
7/2/16 7:44:55.130 PM	mkchromecast[31840]	  File "mkchromecast/cast.pyc", line 41, in __init__
7/2/16 7:44:55.130 PM	mkchromecast[31840]	socket.gaierror: [Errno 8] nodename nor servname provided, or not known
7/2/16 7:45:53.696 PM	systemkeychain[154]	done file: /var/run/systemkeychaincheck.done
7/2/16 7:45:55.037 PM	digest-service[201]		mkey_file: /var/db/krb5kdc/m-key
7/2/16 7:46:07.389 PM	mkchromecast[460]	[0m[04mSelected backend:[0m node
7/2/16 7:46:07.389 PM	mkchromecast[460]	[0m[04mSelected audio codec:[0m mp3
7/2/16 7:46:07.459 PM	mkchromecast[460]	mkchromecast Error
7/2/16 7:46:07.459 PM	mkchromecast[460]	2016-07-02 19:46:07.458 mkchromecast[460:3388] mkchromecast Error
7/2/16 7:46:10.303 PM	mkchromecast[460]	Traceback (most recent call last):
7/2/16 7:46:10.303 PM	mkchromecast[460]	  File "/Applications/mkchromecast.app/Contents/Resources/__boot__.py", line 351, in <module>
7/2/16 7:46:10.303 PM	mkchromecast[460]	    _run()
7/2/16 7:46:10.303 PM	mkchromecast[460]	  File "/Applications/mkchromecast.app/Contents/Resources/__boot__.py", line 336, in _run
7/2/16 7:46:10.303 PM	mkchromecast[460]	    exec(compile(source, path, 'exec'), globals(), globals())
7/2/16 7:46:10.303 PM	mkchromecast[460]	  File "/Applications/mkchromecast.app/Contents/Resources/start_tray.py", line 14, in <module>
7/2/16 7:46:10.303 PM	mkchromecast[460]	    mkchromecast.systray.main()
7/2/16 7:46:10.303 PM	mkchromecast[460]	  File "mkchromecast/systray.pyc", line 623, in main
7/2/16 7:46:10.303 PM	mkchromecast[460]	  File "mkchromecast/systray.pyc", line 38, in __init__
7/2/16 7:46:10.303 PM	mkchromecast[460]	  File "mkchromecast/cast.pyc", line 41, in __init__
7/2/16 7:46:10.303 PM	mkchromecast[460]	socket.gaierror: [Errno 8] nodename nor servname provided, or not known
7/2/16 7:46:57.948 PM	mkchromecast[756]	[0m[04mSelected backend:[0m node
7/2/16 7:46:57.948 PM	mkchromecast[756]	[0m[04mSelected audio codec:[0m mp3
7/2/16 7:46:58.017 PM	mkchromecast[756]	mkchromecast Error
7/2/16 7:46:58.017 PM	mkchromecast[756]	2016-07-02 19:46:58.016 mkchromecast[756:7367] mkchromecast Error
7/2/16 7:47:01.568 PM	mkchromecast[756]	Traceback (most recent call last):
7/2/16 7:47:01.568 PM	mkchromecast[756]	  File "/Applications/mkchromecast.app/Contents/Resources/__boot__.py", line 351, in <module>
7/2/16 7:47:01.568 PM	mkchromecast[756]	    _run()
7/2/16 7:47:01.568 PM	mkchromecast[756]	  File "/Applications/mkchromecast.app/Contents/Resources/__boot__.py", line 336, in _run
7/2/16 7:47:01.568 PM	mkchromecast[756]	    exec(compile(source, path, 'exec'), globals(), globals())
7/2/16 7:47:01.568 PM	mkchromecast[756]	  File "/Applications/mkchromecast.app/Contents/Resources/start_tray.py", line 14, in <module>
7/2/16 7:47:01.568 PM	mkchromecast[756]	    mkchromecast.systray.main()
7/2/16 7:47:01.568 PM	mkchromecast[756]	  File "mkchromecast/systray.pyc", line 623, in main
7/2/16 7:47:01.568 PM	mkchromecast[756]	  File "mkchromecast/systray.pyc", line 38, in __init__
7/2/16 7:47:01.568 PM	mkchromecast[756]	  File "mkchromecast/cast.pyc", line 41, in __init__
7/2/16 7:47:01.568 PM	mkchromecast[756]	socket.gaierror: [Errno 8] nodename nor servname provided, or not known
 
```

**System Details**
```
ProductName:	Mac OS X
ProductVersion:	10.11.5
BuildVersion:	15F34
```

**Comment by muammar** [comment]
Hi @kennykaye . Thanks for the report. The problem is in [line 41 of cast.py](https://github.com/muammar/mkchromecast/blob/master/mkchromecast/cast.py#L41). After researching a bit about the limitations of  [socket.gethostbyname(socket.gethostname())](http://stackoverflow.com/a/31521883/1995261). Given that `netifaces` module is already a dependency of `pychromecast`, it seems to me that the patch below is a possible solution:

```
diff --git a/mkchromecast/cast.py b/mkchromecast/cast.py
index 9e783a2..d29c308 100644
--- a/mkchromecast/cast.py
+++ b/mkchromecast/cast.py
@@ -38,7 +38,20 @@ class casting(object):
             hostname = subprocess.Popen(['hostname', '-I'], stdout=subprocess.PIPE)
             self.ip = hostname.stdout.read().decode('utf-8').strip()
         else:
-            self.ip = socket.gethostbyname(socket.gethostname())
+            try:
+                self.ip = socket.gethostbyname(socket.gethostname())
+            except socket.gaierror:
+                import netifaces
+                interfaces = netifaces.interfaces()
+                for interface in interfaces:
+                    if interface == 'lo':
+                        continue
+                    iface = netifaces.ifaddresses(interface).get(netifaces.AF_INET)
+                    if iface != None and iface[0]['addr'] != '127.0.0.1':
+                        for e in iface:
+                            self.ip = str(e['addr'])
+                            if self.debug == True:
+                                print(':::cast::: netifaces method', self.ip)
```

Before creating an app for you to test, would you let me know if your Mac hardware is newer or older than 2011?.

Thanks.
