### ISSUE TITLE
Ubuntu install

### ISSUE THREAD

**Issue by maxdraki** [muammar/mkchromecast#52]
Hi - I'm trying to get this working following the instructions here: http://www.omgubuntu.co.uk/2016/08/cast-ubuntu-desktop-audio-chromecast - and from your website/ guthub

I've followed the instructions, but when I run mkchromecast from the command line I receive these errors..

```
max@mythos:~/Desktop$ mkchromecast
Traceback (most recent call last):
  File "/usr/bin/mkchromecast", line 8, in <module>
    from mkchromecast.cast import *
  File "/usr/share/mkchromecast/mkchromecast/cast.py", line 13, in <module>
    import pychromecast
  File "/usr/lib/python2.7/dist-packages/pychromecast/__init__.py", line 14, in <module>
    from . import socket_client
  File "/usr/lib/python2.7/dist-packages/pychromecast/socket_client.py", line 22, in <module>
    from . import cast_channel_pb2
  File "/usr/lib/python2.7/dist-packages/pychromecast/cast_channel_pb2.py", line 23, in <module>
    serialized_pb=_b('\n\x12\x63\x61st_channel.proto\x12 extensions.core_api.cast_channel\"\xed\x02\n\x0b\x43\x61stMessage\x12W\n\x10protocol_version\x18\x01 \x02(\x0e\x32=.extensions.core_api.cast_channel.CastMessage.ProtocolVersion\x12\x11\n\tsource_id\x18\x02 \x02(\t\x12\x16\n\x0e\x64\x65stination_id\x18\x03 \x02(\t\x12\x11\n\tnamespace\x18\x04 \x02(\t\x12O\n\x0cpayload_type\x18\x05 \x02(\x0e\x32\x39.extensions.core_api.cast_channel.CastMessage.PayloadType\x12\x14\n\x0cpayload_utf8\x18\x06 \x01(\t\x12\x16\n\x0epayload_binary\x18\x07 \x01(\x0c\"!\n\x0fProtocolVersion\x12\x0e\n\nCASTV2_1_0\x10\x00\"%\n\x0bPayloadType\x12\n\n\x06STRING\x10\x00\x12\n\n\x06\x42INARY\x10\x01\"s\n\rAuthChallenge\x12\x62\n\x13signature_algorithm\x18\x01 \x01(\x0e\x32\x34.extensions.core_api.cast_channel.SignatureAlgorithm:\x0fRSASSA_PKCS1v15\"\xc8\x01\n\x0c\x41uthResponse\x12\x11\n\tsignature\x18\x01 \x02(\x0c\x12\x1f\n\x17\x63lient_auth_certificate\x18\x02 \x02(\x0c\x12 \n\x18intermediate_certificate\x18\x03 \x03(\x0c\x12\x62\n\x13signature_algorithm\x18\x04 \x01(\x0e\x32\x34.extensions.core_api.cast_channel.SignatureAlgorithm:\x0fRSASSA_PKCS1v15\"\xa8\x01\n\tAuthError\x12I\n\nerror_type\x18\x01 \x02(\x0e\x32\x35.extensions.core_api.cast_channel.AuthError.ErrorType\"P\n\tErrorType\x12\x12\n\x0eINTERNAL_ERROR\x10\x00\x12\n\n\x06NO_TLS\x10\x01\x12#\n\x1fSIGNATURE_ALGORITHM_UNAVAILABLE\x10\x02\"\xd5\x01\n\x11\x44\x65viceAuthMessage\x12\x42\n\tchallenge\x18\x01 \x01(\x0b\x32/.extensions.core_api.cast_channel.AuthChallenge\x12@\n\x08response\x18\x02 \x01(\x0b\x32..extensions.core_api.cast_channel.AuthResponse\x12:\n\x05\x65rror\x18\x03 \x01(\x0b\x32+.extensions.core_api.cast_channel.AuthError*J\n\x12SignatureAlgorithm\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x13\n\x0fRSASSA_PKCS1v15\x10\x01\x12\x0e\n\nRSASSA_PSS\x10\x02\x42\x02H\x03')
TypeError: __init__() got an unexpected keyword argument 'syntax'

```
Any ideas?

many thanks
Max

**Comment by muammar** [comment]
What is your ubuntu version?. Normally doing a `apt-get install mkchromecast` would do the job. The problem you are getting is related to pychromecast. What is your version? Did you installed it using `pip` or `apt`?. 

You can check pychromecast's version and source by doing this:

```
$ python                                                                                                                                            
Python 2.7.13 (default, Jan 19 2017, 14:48:08) 
[GCC 6.3.0 20170118] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pychromecast
>>> pychromecast.__version__
'0.7.6'
>>> pychromecast.__file__
'/usr/lib/python2.7/dist-packages/pychromecast/__init__.pyc'

```

**Comment by maxdraki** [comment]
Hi - I'm on Ubuntu 16.10
pychromecast was initially installed using dpkg..

I completely uninstalled mkchromecast and pychromecast (before I think I hadn't uninstalled pychromecast) and reinstalled from the repos and am now getting a slightly different error

```
$ mkchromecast
Traceback (most recent call last):
  File "/usr/bin/mkchromecast", line 8, in <module>
    from mkchromecast.cast import *
  File "/usr/share/mkchromecast/mkchromecast/cast.py", line 13, in <module>
    import pychromecast
  File "/usr/lib/python2.7/dist-packages/pychromecast/__init__.py", line 12, in <module>
    from .config import *  # noqa
  File "/usr/lib/python2.7/dist-packages/pychromecast/config.py", line 6, in <module>
    import requests
ImportError: No module named requests
```

running the command above I'm getting this error

```
$ python
Python 2.7.12+ (default, Sep 17 2016, 12:08:02) 
[GCC 6.2.0 20160914] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pychromecast
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/pychromecast/__init__.py", line 12, in <module>
    from .config import *  # noqa
  File "/usr/lib/python2.7/dist-packages/pychromecast/config.py", line 6, in <module>
    import requests
ImportError: No module named requests
>>> 
```

**Comment by muammar** [comment]
Install python-requests: `sudo apt-get install python-requests` to see if later everything works ok.

**Comment by maxdraki** [comment]
`python-requests is already the newest version (2.10.0-2)..`

any ideas?

**Comment by muammar** [comment]
Mmm. I don't understand why it is not being found in your PYTHONPATH. What about installing it with pip?. It would be: `pip install requests`.

**Comment by maxdraki** [comment]
```
$ pip install requests
Requirement already satisfied: requests in /usr/lib/python2.7/dist-packages
```
and if it's any help I think this is my pythonpath
```
python -c "import sys; print '\n'.join(sys.path)"

/usr/lib/python2.7
/usr/lib/python2.7/plat-x86_64-linux-gnu
/usr/lib/python2.7/lib-tk
/usr/lib/python2.7/lib-old
/usr/lib/python2.7/lib-dynload
/home/max/.local/lib/python2.7/site-packages
/usr/local/lib/python2.7/dist-packages
/usr/lib/python2.7/dist-packages
/usr/lib/python2.7/dist-packages/PILcompat
/usr/lib/python2.7/dist-packages/gtk-2.0
/usr/lib/pymodules/python2.7
/usr/lib/python2.7/dist-packages/ubuntu-sso-client
/usr/lib/python2.7/dist-packages/wx-3.0-gtk2
```

**Comment by muammar** [comment]
I don't understand why pychromecast is not finding `requests`. What happens if you try to `import requests` from a python console?.

**Comment by maxdraki** [comment]
`import requests` completes fine
I now get this error
```
>>> import pychromecast
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/pychromecast/__init__.py", line 14, in <module>
    from . import socket_client
  File "/usr/lib/python2.7/dist-packages/pychromecast/socket_client.py", line 22, in <module>
    from . import cast_channel_pb2
  File "/usr/lib/python2.7/dist-packages/pychromecast/cast_channel_pb2.py", line 23, in <module>
    serialized_pb=_b('\n\x12\x63\x61st_channel.proto\x12 extensions.core_api.cast_channel\"\xed\x02\n\x0b\x43\x61stMessage\x12W\n\x10protocol_version\x18\x01 \x02(\x0e\x32=.extensions.core_api.cast_channel.CastMessage.ProtocolVersion\x12\x11\n\tsource_id\x18\x02 \x02(\t\x12\x16\n\x0e\x64\x65stination_id\x18\x03 \x02(\t\x12\x11\n\tnamespace\x18\x04 \x02(\t\x12O\n\x0cpayload_type\x18\x05 \x02(\x0e\x32\x39.extensions.core_api.cast_channel.CastMessage.PayloadType\x12\x14\n\x0cpayload_utf8\x18\x06 \x01(\t\x12\x16\n\x0epayload_binary\x18\x07 \x01(\x0c\"!\n\x0fProtocolVersion\x12\x0e\n\nCASTV2_1_0\x10\x00\"%\n\x0bPayloadType\x12\n\n\x06STRING\x10\x00\x12\n\n\x06\x42INARY\x10\x01\"s\n\rAuthChallenge\x12\x62\n\x13signature_algorithm\x18\x01 \x01(\x0e\x32\x34.extensions.core_api.cast_channel.SignatureAlgorithm:\x0fRSASSA_PKCS1v15\"\xc8\x01\n\x0c\x41uthResponse\x12\x11\n\tsignature\x18\x01 \x02(\x0c\x12\x1f\n\x17\x63lient_auth_certificate\x18\x02 \x02(\x0c\x12 \n\x18intermediate_certificate\x18\x03 \x03(\x0c\x12\x62\n\x13signature_algorithm\x18\x04 \x01(\x0e\x32\x34.extensions.core_api.cast_channel.SignatureAlgorithm:\x0fRSASSA_PKCS1v15\"\xa8\x01\n\tAuthError\x12I\n\nerror_type\x18\x01 \x02(\x0e\x32\x35.extensions.core_api.cast_channel.AuthError.ErrorType\"P\n\tErrorType\x12\x12\n\x0eINTERNAL_ERROR\x10\x00\x12\n\n\x06NO_TLS\x10\x01\x12#\n\x1fSIGNATURE_ALGORITHM_UNAVAILABLE\x10\x02\"\xd5\x01\n\x11\x44\x65viceAuthMessage\x12\x42\n\tchallenge\x18\x01 \x01(\x0b\x32/.extensions.core_api.cast_channel.AuthChallenge\x12@\n\x08response\x18\x02 \x01(\x0b\x32..extensions.core_api.cast_channel.AuthResponse\x12:\n\x05\x65rror\x18\x03 \x01(\x0b\x32+.extensions.core_api.cast_channel.AuthError*J\n\x12SignatureAlgorithm\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x13\n\x0fRSASSA_PKCS1v15\x10\x01\x12\x0e\n\nRSASSA_PSS\x10\x02\x42\x02H\x03')
TypeError: __init__() got an unexpected keyword argument 'syntax'
>>> ```
:(

**Comment by muammar** [comment]
@maxdraki maybe you can try opening an issue here -> https://github.com/balloob/pychromecast/issues. Pychromecast's developers may help you better than me to solve that problem. I haven't faced it myself :(.

**Comment by maxdraki** [comment]
Thanks Muammar - I'll have a go.. appreciate your help anyway..

I'll post back anything relevant

**Comment by muammar** [comment]
> Thanks Muammar - I'll have a go.. appreciate your help anyway..

Sorry I wasn't of much help. I hope they can help you!. And thanks that would nice if you reported how you fixed the problem in this report.

**Comment by maxdraki** [comment]
So I downloaded pychromecast 0.8 and did 'pip install -r requirements.txt' which updated a few packages and it now seems to work... :) :) (although I'm not entirely sure why!)

Thanks for the help!
