### ISSUE TITLE
CAST_INIT_TIMEOUT on JBL Playlist 150

### ISSUE THREAD

**Issue by basvdburg** [muammar/mkchromecast#72]
Hello,

I have a issue with my new bought **JBL Playlist 150**. It is a speaker with an build-in chromecast (that's what the advertisement told me). The apps on my iPhone which I usually use see the speaker as a Chromecast device, so my guess was that mkchromecast should work with it as well. But i'm running into a weird issue.

While starting mkchromecast, I see the device showing up and mkchromecast appears to be talking with it (tcpdump showed me). But after a while I receive the following error, and I am also not able to play music through the mkchromecast audio device.

`LaunchError: Failed to launch app: CC1AD845, Reason: CAST_INIT_TIMEOUT`

Full output of the command:

```
$ mkchromecast --host 192.168.20.23
Mkchromecast v0.3.7
Creating Pulseaudio Sink...
Open Pavucontrol and Select the Mkchromecast Sink.
Starting Local Streaming Server
[Done]
Selected backend: parec
Selected audio codec: mp3
Default bitrate used: 192k
Default sample rate used: 44100Hz
PID of main process: 2020
PID of streaming process: 2028
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 
List of Devices Available in your Network:
------------------------------------------

Index 	Types 	Friendly Name 
===== 	===== 	============= 
0 	Gcast 	Speaker Woonkamer
 
We will cast to first device in the list above!
 
Speaker Woonkamer
 
 
Information about  Speaker Woonkamer
 
DeviceStatus(friendly_name=u'Speaker Woonkamer', model_name=u'JBL Playlist', manufacturer=u'Harman Kardon', api_version=(1, 0), uuid=UUID('bacf8d73-beea-1eb6-be86-b0814beacbcf'), cast_type='cast')
 
Status of device  Speaker Woonkamer
 
CastStatus(is_active_input=False, is_stand_by=True, volume_level=0.250980406999588, volume_muted=False, app_id=None, display_name=None, namespaces=[], session_id=None, transport_id=None, status_text='')
 
The IP of Speaker Woonkamer is: 192.168.20.110
Your manually entered local IP is: 192.168.20.23
 
The media type string used is: audio/mpeg
 
Cast media controller status
 
CastStatus(is_active_input=False, is_stand_by=True, volume_level=0.250980406999588, volume_muted=False, app_id=None, display_name=None, namespaces=[], session_id=None, transport_id=None, status_text='')
 
Remember to open pavucontrol and select the mkchromecast sink.

Ctrl-C to kill the Application at any Time

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/bas/.local/lib/python2.7/site-packages/pychromecast/socket_client.py", line 339, in run
    if self.run_once() == 1:
  File "/home/bas/.local/lib/python2.7/site-packages/pychromecast/socket_client.py", line 404, in run_once
    function(data)
  File "/home/bas/.local/lib/python2.7/site-packages/pychromecast/socket_client.py", line 825, in <lambda>
    self._block_till_launched(app_id))
  File "/home/bas/.local/lib/python2.7/site-packages/pychromecast/socket_client.py", line 838, in _block_till_launched
    app_id, self.launch_failure.reason))
LaunchError: Failed to launch app: CC1AD845, Reason: CAST_INIT_TIMEOUT


Traceback (most recent call last):
  File "/usr/bin/mkchromecast", line 270, in <module>
    mk()
  File "/usr/bin/mkchromecast", line 51, in __init__
    self.audio_linux()
  File "/usr/bin/mkchromecast", line 72, in audio_linux
    self.show_control(self.control)
  File "/usr/bin/mkchromecast", line 243, in show_control
    input()
  File "<string>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing
```

I think the device communicates a little differently then other "real" chromecast devices, so it's not able to connect.

I am not sure if the issue is in the pychromecast lib or the mkchromecast application. So I filed the issue here first. If i'm at the wrong place, please let me know.

OS: Ubuntu 16.04 LTS (Desktop, running on a libvirt hypervisor)
mkchromecast version: 0.3.7.1-1
pychromecast version: 0.7.3-1

Thank you for the help!

**Comment by muammar** [comment]
Is there a way that you could upgrade to a newer version of pychromecast?.

**Comment by basvdburg** [comment]
I switched to 0.8.1 and that appears to work. I'll close this issue. Thank you for the suggestion :+1:

**Comment by muammar** [comment]
Glad it worked! I will add this to the FAQ.
