### ISSUE TITLE
MultipleChromecastsFoundError

### ISSUE THREAD

**Issue by muammar** [muammar/mkchromecast#8]
Reported in [Google +](https://plus.google.com/u/0/+MadsHansen/posts/9uebVwDTaR2) and causing problem for owners with more than one cast device:

```
Traceback (most recent call last):
  File "/usr/bin/mkchromecast", line 68, in <module>
    cc.get_cc()
  File "/usr/share/mkchromecast/mkchromecast/cast.py", line 213, in get_cc
    self.cast = pychromecast.get_chromecast(self.castto)
  File "/usr/lib/python2.7/dist-packages/pychromecast/__init__.py", line 168, in get_chromecast
    'the filter criteria: {}'.format(filters))
pychromecast.error.MultipleChromecastsFoundError: More than one Chromecast was found specifying the filter criteria: {}
```

**Comment by phraim** [comment]
I've got a couple of chromecasts and noticed the bug. You were close on the fix for it in the cast.py get_chromecast doesn't like the quotes though.

```
-            self.cast = pychromecast.get_chromecast('friendly_name="'+self.castto+'"')
+            self.cast = pychromecast.get_chromecast(friendly_name=self.castto)
```

**Comment by muammar** [comment]
@phraim thank you very much for the comment. I will change the code and release a new version ASAP.
