### ISSUE TITLE
Minor exception from console when SoCo installed

### ISSUE THREAD

**Issue by polyzen** [muammar/mkchromecast#80]
Running `mkchromecast` from the console with SoCo installed causes the exception `TypeError: must be str, not SoCo`.

Edit: [Full output](https://ptpb.pw/fHwe)

Arch Linux, Python 3

**Comment by muammar** [comment]
Mmm. Look at my case:

```
muammar@zarathustra ~/github/mkchromecast [devel] 
± % python3 mkchromecast.py -s                                                                                                                         !10006
Mkchromecast v0.3.8
Creating Pulseaudio Sink...
Open Pavucontrol and Select the Mkchromecast Sink.
Starting Local Streaming Server
[Done]
Selected backend: parec
Selected audio codec: mp3
Default bitrate used: 192k
Default sample rate used: 44100Hz.
PID of main process: 6209
PID of streaming process: 6226
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 
List of Devices Available in your Network:
------------------------------------------

Index 	Types 	Friendly Name 
===== 	===== 	============= 
0 	Gcast 	MonsiTV
1 	Sonos 	Family Room
 
Please, select the Index of the Google Cast device that you want to use:
1
 
Casting to: Family Room
The IP of Family Room is: 192.168.1.182
Your local IP is: 192.168.1.151
192.168.1.182 - - [25/Jun/2017 17:33:47] "GET /stream HTTP/1.1" 200 -
Remember to open pavucontrol and select the mkchromecast sink.

Ctrl-C to kill the Application at any Time

192.168.1.182 - - [25/Jun/2017 17:33:49] "GET /stream HTTP/1.1" 200 -
```

That is on Debian Unstable. This is my soco version:

```
 >>> import soco
>>> soco.__version__
'0.12'
```

What version do you have installed on your Arch?.

**Comment by polyzen** [comment]
Using `-s` does circumvent the issue, here. Same SoCo version. [Here](https://ptpb.pw/fHwe)'s the full output of `mkchromecast`.

**Comment by muammar** [comment]
Ahhh ok, I see. Let me turn off my Chromecast and try again.

**Comment by muammar** [comment]
You are right. Let me fix that. 

```
± % python3 mkchromecast.py --control --encoder-backend ffmpeg -c aac -b 320                                                                           !10026
Mkchromecast v0.3.8
Creating Pulseaudio Sink...
Open Pavucontrol and Select the Mkchromecast Sink.
Starting Local Streaming Server
[Done]
Selected backend: ffmpeg
Selected audio codec: aac
Selected bitrate: 320k
Default sample rate used: 44100Hz.
PID of main process: 22846
PID of streaming process: 22863
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 
List of Devices Available in your Network:
------------------------------------------

Index 	Types 	Friendly Name 
===== 	===== 	============= 
0 	Sonos 	Family Room
 
We will cast to first device in the list above!
 
Traceback (most recent call last):
  File "mkchromecast.py", line 270, in <module>
    mk()
  File "mkchromecast.py", line 51, in __init__
    self.audio_linux()
  File "mkchromecast.py", line 69, in audio_linux
    self.cc.initialize_cast()
  File "/home/muammar/github/mkchromecast/mkchromecast/cast.py", line 170, in initialize_cast
    print(colors.success(self.cast_to))
  File "/home/muammar/github/mkchromecast/mkchromecast/colors.py", line 72, in success
    return color(text, fg_green=True)
  File "/home/muammar/github/mkchromecast/mkchromecast/colors.py", line 50, in color
    color_text += text
TypeError: Can't convert 'SoCo' object to str implicitly
```

**Comment by polyzen** [comment]
Thank you for fixing this so quickly.
