### ISSUE TITLE
Failed to launch app

### ISSUE THREAD

**Issue by rytoj** [muammar/mkchromecast#93]
OS:  Linux Mint 18 Sarah

Getting python exception after running from terminal:
```
...
The IP of KDL-43Wxxxx is: 192.168.0.101
Your local IP is: 192.168.0.11
The media type string used is: audio/mpeg

Traceback (most recent call last):
  File "/usr/bin/mkchromecast", line 270, in <module>
    mk()
  File "/usr/bin/mkchromecast", line 51, in __init__
    self.audio_linux()
  File "/usr/bin/mkchromecast", line 71, in audio_linux
    self.cc.play_cast()
  File "/usr/share/mkchromecast/mkchromecast/cast.py", line 355, in play_cast
    media_controller.play_media('http://' + localip + ':5000/stream', mtype, title=self.title)
  File "/usr/lib/python2.7/dist-packages/pychromecast/controllers/media.py", line 421, in play_media
    self._socket_client.receiver_controller.launch_app(APP_MEDIA_RECEIVER)
  File "/usr/lib/python2.7/dist-packages/pychromecast/socket_client.py", line 810, in launch_app
    app_id, launch_error.reason))
pychromecast.error.LaunchError: Failed to launch app: CC1AD845, Reason: CANCELLED
```

**Comment by muammar** [comment]
That is because your version of pychromecast is too old. Try to update it, and see if that solves the problem.

**Comment by muammar** [comment]
Closing this issue due to inactivity. Please feel free to reopen it.
