### ISSUE TITLE
No module named dial [linux]

### ISSUE THREAD

**Issue by lukaszkups** [muammar/mkchromecast#95]
When I try to run mkchromecast on elementaryOS (linux), I've got an error:

```
Traceback (most recent call last):
  File "mkchromecast.py", line 8, in <module>
    from mkchromecast.cast import *
  File "(...)/mkchromecast/mkchromecast/cast.py", line 15, in <module>
    from pychromecast.dial import reboot
ImportError: No module named dial
```

I've tried to google after this `dial` module, but there's no info on the net currently. Please help

**Comment by muammar** [comment]
What is the version of `pychromecast` that you have right now installed on your system?.

**Comment by lukaszkups** [comment]
`PyChromecast==0.8.1`

**Comment by muammar** [comment]
```
muammar@nuc ~
  % pip install pychromecast                                                                                                                         !10059
Collecting pychromecast
  Using cached PyChromecast-0.8.2-py2.py3-none-any.whl
Collecting requests>=2.0 (from pychromecast)
  Using cached requests-2.18.3-py2.py3-none-any.whl
Collecting six>=1.10.0 (from pychromecast)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting zeroconf>=0.17.7 (from pychromecast)
  Using cached zeroconf-0.19.1-py2.py3-none-any.whl
Collecting protobuf>=3.0.0 (from pychromecast)
  Using cached protobuf-3.3.0-cp27-cp27mu-manylinux1_x86_64.whl
Collecting idna<2.6,>=2.5 (from requests>=2.0->pychromecast)
  Using cached idna-2.5-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests>=2.0->pychromecast)
  Using cached chardet-3.0.4-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests>=2.0->pychromecast)
  Using cached certifi-2017.7.27.1-py2.py3-none-any.whl
Collecting urllib3<1.23,>=1.21.1 (from requests>=2.0->pychromecast)
  Using cached urllib3-1.22-py2.py3-none-any.whl
Collecting netifaces!=0.10.5 (from zeroconf>=0.17.7->pychromecast)
Collecting enum-compat (from zeroconf>=0.17.7->pychromecast)
Collecting setuptools (from protobuf>=3.0.0->pychromecast)
  Using cached setuptools-36.2.7-py2.py3-none-any.whl
Collecting enum34 (from enum-compat->zeroconf>=0.17.7->pychromecast)
  Using cached enum34-1.1.6-py2-none-any.whl
Installing collected packages: idna, chardet, certifi, urllib3, requests, six, netifaces, enum34, enum-compat, zeroconf, setuptools, protobuf, pychromecast
Successfully installed certifi-2017.7.27.1 chardet-3.0.4 enum-compat-0.0.2 enum34-1.1.6 idna-2.5 netifaces-0.10.6 protobuf-3.3.0 pychromecast-0.8.2 requests-2.18.3 setuptools-36.2.7 six-1.10.0 urllib3-1.22 zeroconf-0.19.1
```

Then, executing from command line:

```
muammar@nuc ~/github/mkchromecast [devel]
± % python mkchromecast.py                                                                                                                           !10063
Mkchromecast v0.3.8
Creating Pulseaudio Sink...
Open Pavucontrol and Select the Mkchromecast Sink.
Starting Local Streaming Server
[Done]
Selected backend: parec
Selected audio codec: mp3
Default bitrate used: 192k
Default sample rate used: 44100Hz.
PID of main process: 25838
PID of streaming process: 25853
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
No devices found!
Cleaning up /tmp/...
[Done]
[1]    25838 killed     python mkchromecast.py

muammar@nuc ~/github/mkchromecast [devel]
± % git checkout master                                                                                                                              !10064
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.

muammar@nuc ~/github/mkchromecast [master]
± % python mkchromecast.py                                                                                                                           !10065
Mkchromecast v0.3.7.1
Creating Pulseaudio Sink...
Open Pavucontrol and Select the Mkchromecast Sink.
Starting Local Streaming Server
[Done]
Selected backend: parec
Selected audio codec: mp3
Default bitrate used: 192k
Default sample rate used: 44100Hz
PID of main process: 25953
PID of streaming process: 25967
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
No devices found!
[1]    25953 killed     python mkchromecast.py
```

Then, I opened an iPython terminal and did:

```
muammar@nuc ~
  % ipython                                                                                                                                          !10070
Python 2.7.13+ (default, Jul 19 2017, 18:15:03)
Type "copyright", "credits" or "license" for more information.

IPython 5.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import pychromecast

In [2]: pychromecast.__version_info__
Out[2]: ('0', '7', '6')

In [3]: from pychromecast.dial import reboot

In [4]: pychromecast.__file__
Out[4]: '/home/muammar/.local/lib/python2.7/site-packages/pychromecast/__init__.pyc'

In [5]:
```

I suspect there is a problem with you pychromecast installation?. Can you verify this last import that I did?. 

Note that for some reason __version__ is printing `0.7.6` although the location of the files are the ones reported when I do pip uninstall:

```
muammar@nuc ~
  % pip uninstall pychromecast                                                                                                                       !10071
Uninstalling PyChromecast-0.8.2:
  /home/muammar/.local/lib/python2.7/site-packages/PyChromecast-0.8.2.dist-info/DESCRIPTION.rst
  /home/muammar/.local/lib/python2.7/site-packages/PyChromecast-0.8.2.dist-info/INSTALLER
  /home/muammar/.local/lib/python2.7/site-packages/PyChromecast-0.8.2.dist-info/METADATA
  /home/muammar/.local/lib/python2.7/site-packages/PyChromecast-0.8.2.dist-info/RECORD
  /home/muammar/.local/lib/python2.7/site-packages/PyChromecast-0.8.2.dist-info/WHEEL
  /home/muammar/.local/lib/python2.7/site-packages/PyChromecast-0.8.2.dist-info/metadata.json
  /home/muammar/.local/lib/python2.7/site-packages/PyChromecast-0.8.2.dist-info/top_level.txt
  /home/muammar/.local/lib/python2.7/site-packages/pychromecast/__init__.py
  /home/muammar/.local/lib/python2.7/site-packages/pychromecast/__init__.pyc
  /home/muammar/.local/lib/python2.7/site-packages/pychromecast/authority_keys_pb2.py
  /home/muammar/.local/lib/python2.7/site-packages/pychromecast/authority_keys_pb2.pyc
  /home/muammar/.local/lib/python2.7/site-packages/pychromecast/cast_channel_pb2.py
  /home/muammar/.local/lib/python2.7/site-packages/pychromecast/cast_channel_pb2.pyc
  /home/muammar/.local/lib/python2.7/site-packages/pychromecast/config.py
  /home/muammar/.local/lib/python2.7/site-packages/pychromecast/config.pyc
  /home/muammar/.local/lib/python2.7/site-packages/pychromecast/controllers/__init__.py
  /home/muammar/.local/lib/python2.7/site-packages/pychromecast/controllers/__init__.pyc
  /home/muammar/.local/lib/python2.7/site-packages/pychromecast/controllers/media.py
  /home/muammar/.local/lib/python2.7/site-packages/pychromecast/controllers/media.pyc
  /home/muammar/.local/lib/python2.7/site-packages/pychromecast/controllers/plex.py
  /home/muammar/.local/lib/python2.7/site-packages/pychromecast/controllers/plex.pyc
  /home/muammar/.local/lib/python2.7/site-packages/pychromecast/controllers/youtube.py
  /home/muammar/.local/lib/python2.7/site-packages/pychromecast/controllers/youtube.pyc
  /home/muammar/.local/lib/python2.7/site-packages/pychromecast/dial.py
  /home/muammar/.local/lib/python2.7/site-packages/pychromecast/dial.pyc
  /home/muammar/.local/lib/python2.7/site-packages/pychromecast/discovery.py
  /home/muammar/.local/lib/python2.7/site-packages/pychromecast/discovery.pyc
  /home/muammar/.local/lib/python2.7/site-packages/pychromecast/error.py
  /home/muammar/.local/lib/python2.7/site-packages/pychromecast/error.pyc
  /home/muammar/.local/lib/python2.7/site-packages/pychromecast/logging_pb2.py
  /home/muammar/.local/lib/python2.7/site-packages/pychromecast/logging_pb2.pyc
  /home/muammar/.local/lib/python2.7/site-packages/pychromecast/socket_client.py
  /home/muammar/.local/lib/python2.7/site-packages/pychromecast/socket_client.pyc
Proceed (y/n)?
```

**Comment by diegotrigo** [comment]
not trying to highjack this conversation, but following your comments @muammar, I got the following error msg:
`pi@raspberrypi:~/chromecast/mkchromecast $ sudo python ./mkchromecast.py
Mkchromecast v0.3.7.1
Creating Pulseaudio Sink...
Open Pavucontrol and Select the Mkchromecast Sink.
Traceback (most recent call last):
  File "./mkchromecast.py", line 270, in <module>
    mk()
  File "./mkchromecast.py", line 51, in __init__
    self.audio_linux()
  File "./mkchromecast.py", line 65, in audio_linux
    create_sink()
  File "/home/pi/chromecast/mkchromecast/mkchromecast/pulseaudio.py", line 28, in create_sink
    stderr=subprocess.PIPE
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
`
Any idea?

**Comment by muammar** [comment]
@diegotrigo check this: https://github.com/muammar/mkchromecast/issues/85. I think you need pulseaudio-utils.

**Comment by diegotrigo** [comment]
Awesome Muammar! That fixed the issue. 
I'm now stuck on another one though #103 .

**Comment by muammar** [comment]
I will proceed to close this report due to inactivity. Please feel free to reopen it if needed.
